
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',1,'Days',null,25,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',2,'Days',null,20,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',5,'Days',null,11,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',8,'Days',null,7,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',10,'Days',null,22,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',11,'Days',null,24,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',15,'Days',null,18,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',17,'Days',null,17,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',21,'Days',null,17,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',25,'Days',null,35,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',27,'Days',null,9,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',28,'Days',null,10,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',33,'Days',null,13,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',38,'Days',null,29,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',47,'Days',null,12,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',48,'Days',null,16,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',50,'Days',null,29,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',52,'Days',null,22,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',53,'Days',null,21,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',54,'Days',null,18,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',55,'Days',null,19,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',62,'Days',null,4,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',67,'Days',null,31,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',68,'Days',null,32,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',73,'Days',null,21,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',74,'Days',null,24,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',81,'Days',null,15,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',84,'Days',null,17,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',86,'Days',null,15,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',97,'Days',null,15,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',105,'Days',null,12,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',106,'Days',null,8,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',108,'Days',null,7,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_BENCHMARKS (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','Time To Fill Benchmarks',114,'Days',null,13,null,to_date('27-MAY-17','DD-MON-RR'),to_date('01-APR-17','DD-MON-RR'),null)
/
commit
/