--retiring old Data Mart Spend Code
--Joe Pullifrone IQN-34165 09/26/2016
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE invoice_spend_all_process';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE dm_invoiced_spend';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE dm_invoice_fact_process';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE dm_invoiced_cac_dim_process';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE dm_inv_headcount_fact_process';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE dm_invoiced_spend_all PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/ 

BEGIN
  EXECUTE IMMEDIATE 'DBMS_SCHEDULER.DROP_JOB(''DM_HOURLY_JOBS'',TRUE)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DBMS_SCHEDULER.DROP_PROGRAM(''DM_PG_INVOICE_SPEND_PROCESS'',TRUE)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DBMS_SCHEDULER.DROP_SCHEDULE(''DM_SCHED_HOURLY_JOBS'',TRUE)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/





