/* 
   revoke_execute_on_pkgs_from_ro_iqprodm.sql
   
   Joe Pullifrone
   07/09/2016
   IQN-33370

   This script will revoke execute privs from the RO_IQPRODM user.  

   Script used to create the statements below:

   SELECT 'REVOKE '||privilege||' ON '||table_name||' FROM '||grantee
     FROM user_tab_privs
    WHERE privilege = 'EXECUTE'
      AND grantee = 'RO_IQPRODM'
      AND grantor = 'IQPRODM'
      AND table_name like 'DM%';   

*/

REVOKE EXECUTE ON DM_RATE_EVENTS_PROC FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_TT_FILL_FACT_PROCESS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_WORKER_DIM_PROCESS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_UTILS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_BUYER_SUPP_AGMT_PROCESS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_CUBE_UTILS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_CURRENCY_CONVERSION_DATA FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_FO_METRIC_GRAPH FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_GEO FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_GEOGRAPHIC_RATE_PROCESS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_HEADCOUNT_FACT_PROCESS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_INDEX FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_INVOICED_CAC_DIM_PROCESS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_INVOICED_SPEND FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_INVOICE_FACT_PROCESS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_INV_HEADCOUNT_FACT_PROCESS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_JOB_DIM_PROCESS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_ORG_DIM FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_PERSON_DIM_PROCESS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_POPULATE_SPEND_SUMMARY FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_PROJECT_AGREEMENT_DIM_PRCS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_RATECARD_DIM_PROCESS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_RATE_EVENT FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_SUPP_METRICS FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_UTIL_LOG FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_BOTIMECARD_RATE_EVENT FROM RO_IQPRODM
/
REVOKE EXECUTE ON DM_FOTIMECARD_RATE_EVENT FROM RO_IQPRODM
/