CREATE OR REPLACE VIEW supp_data_and_exclusions_vw
AS
WITH ssc_mv AS (
SELECT mv.release_guid,
       mv.client_guid,
       mv.metric_score_date,
       mv.legacy_source_vms,
       mv.client_name,
       mv.supplier_guid,
       mv.supplier_name,
       mv.release_date,
       mv.requisition_guid,
       mv.requisition_id,
       mv.requisition_create_date,
       mv.requisition_currency,
       mv.requisition_title,
       mv.requisition_industry,
       mv.requisition_country,
       mv.requisition_state,
       mv.requisition_city,
       mv.release_tier,
       mv.requisition_positions,
       mv.requisition_rate,
       mv.requisition_last_ssc_refresh,
       mv.submission_guid, 
       mv.submission_date,
       mv.candidate_name,
       mv.submitted_bill_rate,
       mv.offer_made_date,
       mv.offer_accepted_date,
       mv.offer_rejected_date,
       mv.offer_accepted_rate,
       mv.interview_requested_date,
       mv.interview_scheduled_date,
       mv.interview_date,
       mv.avg_interview_rating,
       mv.assignment_id,
       mv.assignment_status,
       mv.assignment_start_date,
       mv.assignment_pay_rate,
       mv.assignment_bill_rate,
       mv.assignment_unfav_term_date,
       mv.assignment_end_date,
       mv.assignment_end_type,
       mv.submission_last_ssc_refresh
  FROM release_submission_iqn_mv mv
UNION ALL
SELECT mv.release_guid,
       mv.client_guid,
       mv.metric_score_date,
       mv.legacy_source_vms,
       mv.client_name,
       mv.supplier_guid,
       mv.supplier_name,
       mv.release_date,
       mv.requisition_guid,
       mv.requisition_id,
       mv.requisition_create_date,
       mv.requisition_currency,
       mv.requisition_title,
       mv.requisition_industry,
       mv.requisition_country,
       mv.requisition_state,
       mv.requisition_city,
       mv.release_tier,
       mv.requisition_positions,
       mv.requisition_rate,
       mv.requisition_last_ssc_refresh,
       mv.submission_guid, 
       mv.submission_date,
       mv.candidate_name,
       mv.submitted_bill_rate,
       mv.offer_made_date,
       mv.offer_accepted_date,
       mv.offer_rejected_date,
       mv.offer_accepted_rate,
       mv.interview_requested_date,
       mv.interview_scheduled_date,
       mv.interview_date,
       mv.avg_interview_rating,
       mv.assignment_id,
       mv.assignment_status,
       mv.assignment_start_date,
       mv.assignment_pay_rate,
       mv.assignment_bill_rate,
       mv.assignment_unfav_term_date,
       mv.assignment_end_date,
       mv.assignment_end_type,
       mv.submission_last_ssc_refresh
  FROM release_submission_beeline_mv mv)
SELECT cvl.log_in_client_guid,
       cvl.visible_client_guid,
       ssc_mv.release_guid,
       ssc_mv.metric_score_date,
       ssc_mv.legacy_source_vms,
       ssc_mv.client_name,
       ssc_mv.supplier_guid,
       ssc_mv.supplier_name,
       ssc_mv.release_date,
       ssc_mv.requisition_guid,
       xr.requisition_guid AS excluded_requisition_guid,  -- use this col for performance (check for NULL)
       CASE                                               -- use this col for readability
         WHEN xr.requisition_guid IS NULL THEN 'included' 
         ELSE 'excluded' 
       END AS requisition_inclusion_status,
       ssc_mv.requisition_id,
       ssc_mv.requisition_create_date,
       ssc_mv.requisition_currency,
       ssc_mv.requisition_title,
       ssc_mv.requisition_industry,
       ssc_mv.requisition_country,
       ssc_mv.requisition_state,
       ssc_mv.requisition_city,
       ssc_mv.release_tier,
       ssc_mv.requisition_positions,
       ssc_mv.requisition_rate,
       ssc_mv.requisition_last_ssc_refresh,
       ssc_mv.submission_guid,
       xc.candidate_guid AS excluded_submission_guid,  -- use this col for performance (check for NULL)
       CASE                                            -- use this col for human readability 
         WHEN xc.candidate_guid IS NULL THEN 'included'
         ELSE 'excluded'
       END AS submission_inclusion_status,  
       ssc_mv.submission_date,
       ssc_mv.candidate_name,
       ssc_mv.submitted_bill_rate,
       ssc_mv.offer_made_date,
       ssc_mv.offer_accepted_date,
       ssc_mv.offer_rejected_date,
       ssc_mv.offer_accepted_rate,
       ssc_mv.interview_requested_date,
       ssc_mv.interview_scheduled_date,
       ssc_mv.interview_date,
       ssc_mv.avg_interview_rating,
       ssc_mv.assignment_id,
       ssc_mv.assignment_status,
       ssc_mv.assignment_start_date,
       ssc_mv.assignment_pay_rate,
       ssc_mv.assignment_bill_rate,
       ssc_mv.assignment_unfav_term_date,
       ssc_mv.assignment_end_date,
       ssc_mv.assignment_end_type,
       ssc_mv.submission_last_ssc_refresh
  FROM client_visibility_list cvl,
       ssc_mv,
       excluded_requisition xr,
       excluded_candidate xc
 WHERE cvl.visible_client_guid = ssc_mv.client_guid
   AND ssc_mv.requisition_guid = xr.requisition_guid(+) -- outer to get requisitions which are NOT excluded
   AND ssc_mv.submission_guid  = xc.candidate_guid(+)   -- outer to get candidates which are NOT excluded
/

