CREATE GLOBAL TEMPORARY TABLE lego_invoice_detail_gtt 
(
invoice_id                      NUMBER(38), 
extract_id                      VARCHAR2(50 CHAR), 
msg_id                          NUMBER(38), 
invoice_detail_id               NUMBER(38), 
invoice_header_fk               NUMBER(38), 
invoiceable_expenditure_fk      NUMBER(38), 
invoiceable_expenditure_txn_fk  NUMBER(38), 
expense_report_fk               NUMBER(38), 
timecard_fk                     NUMBER(38), 
payment_request_fk              NUMBER(38), 
milestone_invoice_fk            NUMBER(38), 
assignment_continuity_fk        NUMBER(38), 
expenditure_number              VARCHAR2(60 CHAR), 
supplier_management_fees_fk     NUMBER(38), 
buyer_management_fees_fk        NUMBER(38), 
total_management_fees_fk        NUMBER(38), 
buyer_fee_amount                NUMBER(38,2), 
supplier_fee_amount             NUMBER(38,2), 
total_fee_amount                NUMBER(38,2), 
buyer_invoice_number            VARCHAR2(35 CHAR), 
is_transaction_fees_subset      NUMBER(38,2), 
currency_unit_fk                NUMBER(38,2), 
currency_code                   VARCHAR2(10 CHAR), 
rate_identifier_fk              NUMBER(38,2), 
quantity                        NUMBER(38,2), 
buyer_adjusted_bill_rate        NUMBER(38,2), 
supplier_reimbursement_rate     NUMBER(38,2), 
regular_hours                   NUMBER(38,2), 
ot_hours                        NUMBER(38,2), 
dt_hours                        NUMBER(38,2), 
regular_rate                    NUMBER(38,2), 
ot_rate                         NUMBER(38,2), 
dt_rate                         NUMBER(38,2), 
expenditure_type                VARCHAR2(100 CHAR), 
invoice_transaction_type        VARCHAR2(100 CHAR), 
expense_type_name               VARCHAR2(40 CHAR), 
payment_type_name               VARCHAR2(50 CHAR), 
flexrate_type                   VARCHAR2(10 CHAR), 
flexrate_buyer_amount           NUMBER(38,2), 
flexrate_supplier_amount        NUMBER(38,2), 
flexrate_exp_type_name_fk       VARCHAR2(90 CHAR), 
reversed_expenditure_txn_fk     NUMBER(38), 
invoice_date                    DATE, 
week_ending_date                DATE, 
expenditure_date                DATE, 
bill_through_date               DATE, 
buyer_bus_org_fk                NUMBER(38),
buyer_bus_org_name              VARCHAR2(100 CHAR), 
buyer_bus_org_bill_to_addr_fk   NUMBER(38), 
buyer_bus_org_tax_id            VARCHAR2(30 CHAR), 
supplier_bus_org_fk             NUMBER(38), 
supplier_bus_org_name           VARCHAR2(100 CHAR), 
supplier_bus_org_pymnt_addr_fk  NUMBER(38), 
supplier_bus_org_tax_id         VARCHAR2(30 CHAR), 
payment_amount                  NUMBER(38,2), 
markup_amount                   NUMBER(38,2), 
bill_amount                     NUMBER(38,2),
buyer_adjusted_amount           NUMBER(38,2), 
supplier_reimbursement_amount   NUMBER(38,2), 
candidate_id                    NUMBER(38), 
candidate_first_name            VARCHAR2(100 CHAR), 
candidate_last_name             VARCHAR2(100 CHAR), 
unique_resource_id              VARCHAR2(100 CHAR), 
state_fk                        NUMBER(38,0), 
is_adjustment                   NUMBER(1), 
customer_supplier_internal_id   VARCHAR2(50 CHAR), 
invoiced_buyer_supplier_id      NUMBER(38), 
rate_unit_fk                    NUMBER(38), 
base_bill_rate                  NUMBER(38,2), 
service_identifier              VARCHAR2(40 CHAR), 
assignment_bonus_fk             NUMBER(38), 
direct_hire_agmt_fk             NUMBER(38), 
reversing_expenditure_txn_fk    NUMBER(38), 
is_for_backoffice_reversal      NUMBER(1), 
reversed_flexrate_inv_dtl_fk    NUMBER(38), 
project_agreement_fk            NUMBER(38), 
buyer_taxable_country           NUMBER(38), 
accounting_code                 VARCHAR2(260 CHAR), 
cac1_segment1_value             VARCHAR2(150 CHAR), 
cac1_segment2_value             VARCHAR2(150 CHAR), 
cac1_segment3_value             VARCHAR2(150 CHAR), 
cac1_segment4_value             VARCHAR2(150 CHAR), 
cac1_segment5_value             VARCHAR2(150 CHAR), 
cac2_segment1_value             VARCHAR2(150 CHAR), 
cac2_segment2_value             VARCHAR2(150 CHAR), 
cac2_segment3_value             VARCHAR2(150 CHAR), 
cac2_segment4_value             VARCHAR2(150 CHAR), 
cac2_segment5_value             VARCHAR2(150 CHAR), 
invalidating_event_desc_fk      NUMBER(38), 
base_pay_rate                   NUMBER(38,2), 
flexrate_mgmt_fee_amount        NUMBER(38,2), 
tax_rule_fk                     NUMBER(38), 
exp_detail_comment              VARCHAR2(4000 CHAR), 
expenditure_category            VARCHAR2(4000 CHAR), 
invoiced_agreement_fk           NUMBER(38), 
flexrate_rule_usage_fk          NUMBER(38), 
flex_rule_fk                    NUMBER(38), 
iqn_invoice_number              VARCHAR2(35 CHAR), 
buyer_tax_amount                NUMBER(38,2), 
supplier_tax_amount             NUMBER(38,2), 
mgmt_fee_tax_amount             NUMBER(38,2), 
mgmt_fee_rebate_amount          NUMBER(38,2), 
is_vat_applied_on_fee           NUMBER(1), 
buyer_discount_amount           NUMBER(38,2), 
supplier_discount_amount        NUMBER(38,2), 
invoiceable_exp_owner_state_fk  NUMBER(38), 
payee_business_org_fk           NUMBER(38), 
is_iqn_mgmt_fee_payee           NUMBER(1), 
expense_report_line_item_fk     NUMBER(38), 
milestone_invoice_detail_fk     NUMBER(38),
timecard_entry_fk               NUMBER(38),
buyer_fee_calc_percent          NUMBER(38,2), 
supplier_fee_calc_percent       NUMBER(38,2),  
total_fee_calc_percent          NUMBER(38,2),  
approval_date                   DATE, 
candidate_middle_name           VARCHAR2(100 CHAR), 
partial_rate_percent            NUMBER(38,2),  
position_title                  VARCHAR2(128 CHAR), 
flexrate_buyer_rate             NUMBER(38,2),  
cs_hours                        NUMBER(38,2),  
cs_rate                         NUMBER(38,2), 
purchase_order                  VARCHAR2(50 CHAR), 
custom_invoiceable_fk           NUMBER(38), 
ariba_network_id                VARCHAR2(100 CHAR), 
manager_user_fk                 NUMBER(38),  
manager_first_name              VARCHAR2(100 CHAR), 
manager_last_name               VARCHAR2(100 CHAR), 
sales_tax_amt_rollup            NUMBER(38,2),  
discount_amt_rollup             NUMBER(38,2),  
mfr_amt_rollup                  NUMBER(38,2),  
sales_tax_amt_on_fee_rollup     NUMBER(38,2),  
debit_credit_indicator          NUMBER(1), 
curr_conv_info_fk               NUMBER(38),  
ap_invoice_number               VARCHAR2(100 CHAR), 
cac1_segment1_oid               NUMBER(38), 
cac1_segment2_oid               NUMBER(38), 
cac1_segment3_oid               NUMBER(38), 
cac1_segment4_oid               NUMBER(38), 
cac1_segment5_oid               NUMBER(38), 
cac2_segment1_oid               NUMBER(38), 
cac2_segment2_oid               NUMBER(38), 
cac2_segment3_oid               NUMBER(38), 
cac2_segment4_oid               NUMBER(38), 
cac2_segment5_oid               NUMBER(38), 
cac1_segment1_desc              VARCHAR2(150 CHAR), 
cac1_segment2_desc              VARCHAR2(150 CHAR), 
cac1_segment3_desc              VARCHAR2(150 CHAR), 
cac1_segment4_desc              VARCHAR2(150 CHAR), 
cac1_segment5_desc              VARCHAR2(150 CHAR), 
cac2_segment1_desc              VARCHAR2(150 CHAR), 
cac2_segment2_desc              VARCHAR2(150 CHAR), 
cac2_segment3_desc              VARCHAR2(150 CHAR), 
cac2_segment4_desc              VARCHAR2(150 CHAR), 
cac2_segment5_desc              VARCHAR2(150 CHAR), 
org_sub_classification          VARCHAR2(256 CHAR), 
supplier_taxable_country        NUMBER(38), 
configuration_edition_fk        NUMBER(38), 
project_number                  VARCHAR2(260 CHAR), 
payment_request_invdtl_fk       NUMBER(38) 
) 
ON COMMIT PRESERVE ROWS 
NOPARALLEL
/
