CREATE TABLE DM_OCCUPATION_HIERARCHY 
   (STD_JOB_TITLE_ID NUMBER NOT NULL, 
	STD_OCCUPATION_ID NUMBER NOT NULL, 
	STD_JOB_CATEGORY_ID NUMBER NOT NULL, 
	STD_SUB_CATEGORY_ID NUMBER NOT NULL
   )
/
ALTER TABLE DM_OCCUPATION_HIERARCHY ADD CONSTRAINT DM_OCC_HIERARCHY_PK PRIMARY KEY (STD_JOB_TITLE_ID)
/
ALTER TABLE DM_OCCUPATION_HIERARCHY ADD CONSTRAINT DM_OCC_HIERARCHY_JC_FK FOREIGN KEY (STD_JOB_CATEGORY_ID)
	  REFERENCES DM_JOB_CATEGORY (STD_JOB_CATEGORY_ID)
/
  ALTER TABLE DM_OCCUPATION_HIERARCHY ADD CONSTRAINT DM_OCC_HIERARCH_OCC_FK FOREIGN KEY (STD_OCCUPATION_ID)
	  REFERENCES DM_STD_OCCUPATION (STD_OCCUPATION_ID)
/
  ALTER TABLE DM_OCCUPATION_HIERARCHY ADD CONSTRAINT DM_OCC_HIERARCY_JT_FK FOREIGN KEY (STD_JOB_TITLE_ID)
	  REFERENCES DM_JOB_TITLES (STD_JOB_TITLE_ID)
/	  
  ALTER TABLE DM_OCCUPATION_HIERARCHY ADD CONSTRAINT DM_OCC_HIERARHCY_SC_FK FOREIGN KEY (STD_SUB_CATEGORY_ID)
	  REFERENCES DM_STD_SUB_CATEGORY (STD_SUB_CATEGORY_ID)
/	  
