
Insert into IQPRODM.DM_JOB_TITLES (STD_JOB_TITLE_ID,STD_JOB_TITLE_DESC,LAST_UPDATE_DATE,STD_JOB_DESC,STD_JOB_CATEGORY_ID,IS_DELETED) values (135,'Production Manager',to_date('13-OCT-16','DD-MON-RR'),NULL,7,'N')
/
Insert into IQPRODM.DM_JOB_TITLES (STD_JOB_TITLE_ID,STD_JOB_TITLE_DESC,LAST_UPDATE_DATE,STD_JOB_DESC,STD_JOB_CATEGORY_ID,IS_DELETED) values (136,'Data Scientist',to_date('13-OCT-16','DD-MON-RR'),NULL,6,'N')
/
Insert into IQPRODM.DM_JOB_TITLES (STD_JOB_TITLE_ID,STD_JOB_TITLE_DESC,LAST_UPDATE_DATE,STD_JOB_DESC,STD_JOB_CATEGORY_ID,IS_DELETED) values (137,'IT Systems Technician',to_date('13-OCT-16','DD-MON-RR'),NULL,6,'N')
/
Insert into IQPRODM.DM_JOB_TITLES (STD_JOB_TITLE_ID,STD_JOB_TITLE_DESC,LAST_UPDATE_DATE,STD_JOB_DESC,STD_JOB_CATEGORY_ID,IS_DELETED) values (138,'UI/UX Designer',to_date('13-OCT-16','DD-MON-RR'),NULL,6,'N')
/
Insert into IQPRODM.DM_JOB_TITLES (STD_JOB_TITLE_ID,STD_JOB_TITLE_DESC,LAST_UPDATE_DATE,STD_JOB_DESC,STD_JOB_CATEGORY_ID,IS_DELETED) values (139,'Scientist R&D',to_date('13-OCT-16','DD-MON-RR'),NULL,3,'N')
/
Insert into IQPRODM.DM_JOB_TITLES (STD_JOB_TITLE_ID,STD_JOB_TITLE_DESC,LAST_UPDATE_DATE,STD_JOB_DESC,STD_JOB_CATEGORY_ID,IS_DELETED) values (140,'Build Release Engineer',to_date('13-OCT-16','DD-MON-RR'),NULL,6,'N')
/
Insert into IQPRODM.DM_JOB_TITLES (STD_JOB_TITLE_ID,STD_JOB_TITLE_DESC,LAST_UPDATE_DATE,STD_JOB_DESC,STD_JOB_CATEGORY_ID,IS_DELETED) values (141,'Specialized Engineering Consultant',to_date('13-OCT-16','DD-MON-RR'),NULL,3,'N')
/
commit
/
