Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (0,0,0,0)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (1,1,4,12)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (2,2,4,13)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (3,2,4,13)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (4,2,4,13)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (5,5,1,1)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (6,6,2,2)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (7,108,7,21)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (8,8,4,12)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (9,31,2,6)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (10,10,6,15)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (11,11,2,3)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (12,12,2,4)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (13,69,2,7)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (14,14,2,4)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (15,15,2,5)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (16,16,6,16)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (17,17,1,1)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (18,18,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (19,56,6,19)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (20,53,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (21,21,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (22,5,1,1)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (23,5,1,1)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (24,5,1,1)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (25,25,4,12)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (26,62,7,23)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (27,27,7,21)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (28,28,2,2)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (30,21,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (31,31,2,6)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (32,62,7,23)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (33,33,7,22)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (35,45,2,4)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (36,108,7,21)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (37,5,1,1)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (38,38,2,7)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (39,39,2,1)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (40,40,2,7)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (41,62,7,23)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (42,42,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (43,42,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (44,62,7,23)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (45,45,2,4)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (46,46,6,15)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (47,47,6,15)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (48,48,6,15)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (49,5,1,1)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (50,50,2,6)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (51,50,2,6)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (52,52,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (53,53,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (54,54,6,18)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (55,55,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (56,56,6,19)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (57,55,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (58,58,6,15)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (59,42,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (60,5,1,1)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (61,61,2,4)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (62,62,7,23)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (63,25,4,12)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (64,53,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (65,65,1,1)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (67,67,2,4)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (68,68,2,4)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (69,69,2,7)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (70,84,7,3)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (71,28,2,2)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (72,72,2,4)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (73,73,3,9)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (74,74,3,10)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (75,105,3,11)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (79,79,7,22)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (80,25,4,12)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (81,81,4,13)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (82,1,4,12)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (84,84,2,3)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (85,2,4,13)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (86,86,2,4)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (87,1,4,12)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (89,53,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (92,56,6,19)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (93,111,2,4)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (95,54,6,18)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (96,81,1,13)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (97,97,7,23)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (99,10,6,15)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (100,100,6,20)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (105,105,3,11)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (106,106,7,24)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (107,111,2,4)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (108,108,7,21)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (110,84,7,3)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (111,111,2,4)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (112,112,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (113,68,2,4)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (114,114,2,5)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (115,115,4,12)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (116,116,2,8)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (117,117,3,11)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (119,119,3,9)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (122,127,2,8)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (123,123,1,26)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (124,25,4,12)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (125,125,2,4)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (126,134,0,0)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (127,127,2,8)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (128,81,1,13)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (129,81,4,13)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (130,81,4,13)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (131,81,4,13)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (132,81,4,13)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (133,134,0,0)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (134,134,0,0)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (135,135,7,21)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (136,136,6,16)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (137,137,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (138,138,6,15)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (139,139,3,10)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (140,140,6,17)
/
Insert into DM_OCCUPATION_HIERARCHY (STD_JOB_TITLE_ID,STD_OCCUPATION_ID,STD_JOB_CATEGORY_ID,STD_SUB_CATEGORY_ID) values (141,141,3,10)
/
COMMIT
/
