CREATE OR REPLACE FORCE VIEW LEGO_RATECARD_VW 
AS
SELECT r.rate_card_id,
       r.rate_card_identifier,
       r.rate_card_identifier_id,
       r.buyer_org_id,
       r.source_template_id,
       r.active,
       r.active_id,
       r.uses_factors,
       r.uses_ranges,
       r.lower_rate_set_id,
       r.upper_rate_set_id,
       r.rate_unit_id,
       r.rate_unit,
       r.pay_rate_min,
       ROUND(r.pay_rate_min * NVL(cc.conversion_rate, 1), 2) AS pay_rate_min_cc,
       r.pay_rate_ot_min,
       ROUND(r.pay_rate_ot_min * NVL(cc.conversion_rate, 1), 2) AS pay_rate_ot_min_cc,
       r.pay_factor_ot_min,
       r.pay_rate_dt_min,
       ROUND(r.pay_rate_dt_min * NVL(cc.conversion_rate, 1), 2) AS pay_rate_dt_min_cc,
       r.pay_factor_dt_min,
       r.bill_rate_min,
       ROUND(r.bill_rate_min * NVL(cc.conversion_rate, 1), 2) AS bill_rate_min_cc,
       r.bill_rate_ot_min,
       ROUND(r.bill_rate_ot_min * NVL(cc.conversion_rate, 1), 2) AS bill_rate_ot_min_cc,
       r.bill_factor_ot_min,
       r.bill_rate_dt_min,
       ROUND(r.bill_rate_dt_min * NVL(cc.conversion_rate, 1), 2) AS bill_rate_dt_min_cc,
       r.bill_factor_dt_min,
       r.markup_min,
       r.markup_ot_min,
       r.markup_dt_min,
       r.custom_pay_rate_min,
       ROUND(r.custom_pay_rate_min * NVL(cc.conversion_rate, 1), 2) AS custom_pay_rate_min_cc,
       r.custom_markup_min,
       r.custom_bill_rate_min,
       ROUND(r.custom_bill_rate_min * NVL(cc.conversion_rate, 1), 2) AS custom_bill_rate_min_cc,
       r.pay_rate_max,
       ROUND(r.pay_rate_max * NVL(cc.conversion_rate, 1), 2) AS pay_rate_max_cc,
       r.pay_rate_ot_max,
       ROUND(r.pay_rate_ot_max * NVL(cc.conversion_rate, 1), 2) AS pay_rate_ot_max_cc,
       r.pay_factor_ot_max,
       r.pay_rate_dt_max,
       ROUND(r.pay_rate_dt_max * NVL(cc.conversion_rate, 1), 2) AS pay_rate_dt_max_cc,
       r.pay_factor_dt_max,
       r.bill_rate_max,
       ROUND(r.bill_rate_max * NVL(cc.conversion_rate, 1), 2) AS bill_rate_max_cc,
       r.bill_rate_ot_max,
       ROUND(r.bill_rate_ot_max * NVL(cc.conversion_rate, 1), 2) AS bill_rate_ot_max_cc,
       r.bill_factor_ot_max,
       r.bill_rate_dt_max,
       ROUND(r.bill_rate_dt_max * NVL(cc.conversion_rate, 1), 2) AS bill_rate_dt_max_cc,
       r.bill_factor_dt_max,
       r.markup_max,
       r.markup_ot_max,
       r.markup_dt_max,
       r.custom_pay_rate_max,
       ROUND(r.custom_pay_rate_max * NVL(cc.conversion_rate, 1), 2) AS custom_pay_rate_max_cc,
       r.custom_markup_max,
       r.custom_bill_rate_max,
       ROUND(r.custom_bill_rate_max * NVL(cc.conversion_rate, 1), 2) AS custom_bill_rate_max_cc,
       r.ratecard_currency_id,
       r.ratecard_currency,
       NVL(cc.converted_currency_id, r.ratecard_currency_id) AS to_ratecard_currency_id,
       NVL(cc.converted_currency_code, r.ratecard_currency)  AS to_ratecard_currency,
       ROUND(NVL(cc.conversion_rate, 1), 6) AS conversion_rate
  FROM lego_ratecard r,
       lego_currency_conv_rates_vw cc
 WHERE r.ratecard_currency_id = cc.original_currency_id(+)
/


