CREATE OR REPLACE FORCE VIEW LEGO_ASSIGNMENT_CAC_VW AS
SELECT lac.assignment_continuity_id,
       lac.cac_collection_id,
       lac.cac_id,
       lac.buyer_org_id,
       lac.cac_kind,
       lac.primary_active_cac,
       lac.cac_start_date,
       lac.cac_end_date,
       lc.cac_segment_1_value   AS cac1_segment_1_value,
       lc.cac_segment_2_value   AS cac1_segment_2_value,
       lc.cac_segment_3_value   AS cac1_segment_3_value,
       lc.cac_segment_4_value   AS cac1_segment_4_value,
       lc.cac_segment_5_value   AS cac1_segment_5_value,
       lc.cac_segment_1_desc    AS cac1_segment_1_desc,
       lc.cac_segment_2_desc    AS cac1_segment_2_desc,
       lc.cac_segment_3_desc    AS cac1_segment_3_desc,
       lc.cac_segment_4_desc    AS cac1_segment_4_desc,
       lc.cac_segment_5_desc    AS cac1_segment_5_desc,
       NULL                     AS cac2_segment_1_value,
       NULL                     AS cac2_segment_2_value,
       NULL                     AS cac2_segment_3_value,
       NULL                     AS cac2_segment_4_value,
       NULL                     AS cac2_segment_5_value,
       NULL                     AS cac2_segment_1_desc,
       NULL                     AS cac2_segment_2_desc,
       NULL                     AS cac2_segment_3_desc,
       NULL                     AS cac2_segment_4_desc,
       NULL                     AS cac2_segment_5_desc
 FROM lego_assignment_cac lac, lego_cac lc
WHERE lac.cac_guid = lc.cac_guid
  AND cac_kind = 1
UNION ALL
SELECT lac.assignment_continuity_id,
       lac.cac_collection_id,
       lac.cac_id,
       lac.buyer_org_id,
       lac.cac_kind,
       lac.primary_active_cac,
       lac.cac_start_date,
       lac.cac_end_date,
       NULL                     AS cac1_segment_1_value,
       NULL                     AS cac1_segment_2_value,
       NULL                     AS cac1_segment_3_value,
       NULL                     AS cac1_segment_4_value,
       NULL                     AS cac1_segment_5_value,
       NULL                     AS cac1_segment_1_desc,
       NULL                     AS cac1_segment_2_desc,
       NULL                     AS cac1_segment_3_desc,
       NULL                     AS cac1_segment_4_desc,
       NULL                     AS cac1_segment_5_desc,
       lc.cac_segment_1_value   AS cac2_segment_1_value,
       lc.cac_segment_2_value   AS cac2_segment_2_value,
       lc.cac_segment_3_value   AS cac2_segment_3_value,
       lc.cac_segment_4_value   AS cac2_segment_4_value,
       lc.cac_segment_5_value   AS cac2_segment_5_value,
       lc.cac_segment_1_desc    AS cac2_segment_1_desc,
       lc.cac_segment_2_desc    AS cac2_segment_2_desc,
       lc.cac_segment_3_desc    AS cac2_segment_3_desc,
       lc.cac_segment_4_desc    AS cac2_segment_4_desc,
       lc.cac_segment_5_desc    AS cac2_segment_5_desc
 FROM lego_assignment_cac lac, lego_cac lc
WHERE lac.cac_guid = lc.cac_guid
  AND cac_kind = 2
/

-----------------------------------------

CREATE OR REPLACE FORCE VIEW lego_assignment_vw 
AS
SELECT assignment_continuity_id,
       contractor_person_id,
       hiring_mgr_person_id,
       act_hiring_mgr_person_id,
       buyer_org_id,
       supplier_org_id,
       job_id,
       candidate_id,
       assignment_type,
       amendment_id,
       amendment_in_process_num,
       assignment_start_dt,
       assignment_end_dt,
       assignment_actual_end_dt,
       actual_end_dt_no_deflt,
       last_modified_date,
       assignment_duration,
       CASE 
          WHEN assignment_actual_end_dt >= TRUNC(SYSDATE) THEN assignment_actual_end_dt - TRUNC(SYSDATE)
          ELSE NULL
       END AS days_until_assignment_end,
       assignment_state_id,
       NVL(as_jcl.constant_description, assignments.assignment_state) AS assignment_state,
       approval_state_id,
       NVL(ass_app_jcl.constant_description, assignments.approval_state) AS approval_state,
       sourcing_method,
       candidate_sourcing_method_id,
       NVL(csm_jcl.constant_description, assignments.candidate_sourcing_method) AS candidate_sourcing_method,
       assignments.current_edition_id,
       cac_collection1_id,
       cac_collection2_id,
       contact_info_id,
       address_guid,
       cam_person_id,
       sar_person_id,
       project_id,
       project_agreement_id,
       creator_person_id,
       timecard_approval_workflow_id,
       evaluation_id,
       procurement_wkfl_edition_id,
       assign_requisition_type,
       approval_workflow_id,
       worker_id,
       work_order_id,
       udf_collection_id,
       wov_udf_collection_id,
       worker_ed_udf_collection_id,
       onboard_allowed,
       onboard_checklist_id,
       buyer_resource_id,
       org_sub_classification,
       CASE 
          WHEN assignments.jc_type = 'CONSTANT' THEN NVL(jc_jcl.constant_description, assignments.jc_description) 
          WHEN assignments.jc_type = 'CUSTOM'   THEN NVL(jc_cust.assign_jc_description, NVL(jc_jcl.constant_description, assignments.jc_description))
          ELSE assignments.jc_description
       END AS assign_jc_description,
       NVL(ass_title_jcl.assign_job_title, assignments.assign_job_title) AS assign_job_title,
       assign_job_title_lp,
       phase_type_id,
       NVL(cp_jcl.constant_description, assignments.current_phase) AS current_phase,
       est_total_budgeted_amount,
       ROUND(est_total_budgeted_amount * NVL(cc.conversion_rate, 1), 2) AS est_total_budgeted_amount_cc,
       est_wo_budget_remain_approved,
       ROUND(est_wo_budget_remain_approved * NVL(cc.conversion_rate, 1), 2) AS est_wo_bdgt_remain_approved_cc,
       assignment_end_reason_codes,
       --NVL(yesno1_jcl.constant_description, assignments.eval_res_perform_duties)  
        --NULL AS eval_res_perform_duties,
       --NVL(yesno2_jcl.constant_description, assignments.eval_res_use_again)       
        --NULL AS eval_res_use_again,
       --NVL(yesno3_jcl.constant_description, assignments.eval_res_for_another_pos) 
        --NULL AS eval_res_for_another_pos,
       --rates
       rate_type_id,
       NVL(rate_type_jcl.constant_description, assignments.rate_type)  AS rate_type,
       reg_bill_rate,
       ROUND(reg_bill_rate * NVL(cc.conversion_rate, 1), 2) AS reg_bill_rate_cc,
       bill_rate_ot,
       ROUND(bill_rate_ot * NVL(cc.conversion_rate, 1), 2) AS bill_rate_ot_cc,
       bill_rate_dt,
       ROUND(bill_rate_dt * NVL(cc.conversion_rate, 1), 2) AS bill_rate_dt_cc,
       bill_rate_custom,
       ROUND(bill_rate_custom * NVL(cc.conversion_rate, 1), 2) AS bill_rate_custom_cc,
       adjusted_bill_rate,
       ROUND(adjusted_bill_rate * NVL(cc.conversion_rate, 1), 2) AS adjusted_bill_rate_cc,
       adjusted_bill_rate_ot,
       ROUND(adjusted_bill_rate_ot * NVL(cc.conversion_rate, 1), 2) AS adjusted_bill_rate_ot_cc,
       adjusted_bill_rate_dt,
       ROUND(adjusted_bill_rate_dt * NVL(cc.conversion_rate, 1), 2) AS adjusted_bill_rate_dt_cc,
       adjusted_bill_rate_custom,
       ROUND(adjusted_bill_rate_custom * NVL(cc.conversion_rate, 1), 2) AS adjusted_bill_rate_custom_cc,
       supplier_reimb_bill_rate,
       ROUND(supplier_reimb_bill_rate * NVL(cc.conversion_rate, 1), 2) AS supplier_reimb_bill_rate_cc,
       supplier_reimb_bill_rate_ot,
       ROUND(supplier_reimb_bill_rate_ot * NVL(cc.conversion_rate, 1), 2) AS supplier_reimb_bill_rate_ot_cc,
       supplier_reimb_bill_rate_dt,
       ROUND(supplier_reimb_bill_rate_dt * NVL(cc.conversion_rate, 1), 2) AS supplier_reimb_bill_rate_dt_cc,
       supplier_reimb_bill_rate_cust,
       ROUND(supplier_reimb_bill_rate_cust * NVL(cc.conversion_rate, 1), 2) AS supplr_reimb_bill_rate_cust_cc,       
       reg_pay_rate,
       ROUND(reg_pay_rate * NVL(cc.conversion_rate, 1), 2) AS reg_pay_rate_cc,
       pay_rate_ot,
       ROUND(pay_rate_ot * NVL(cc.conversion_rate, 1), 2) AS pay_rate_ot_cc,
       pay_rate_dt,
       ROUND(pay_rate_dt * NVL(cc.conversion_rate, 1), 2) AS pay_rate_dt_cc,
       pay_rate_custom,
       ROUND(pay_rate_custom * NVL(cc.conversion_rate, 1), 2) AS pay_rate_custom_cc,
       reg_mark_up,
       mark_up_ot,
       mark_up_dt,
       mark_up_custom,       
       assignment_currency_id,
       assignment_currency,
       NVL(cc.converted_currency_id, assignment_currency_id) AS to_assignment_currency_id,
       NVL(cc.converted_currency_code, assignment_currency)  AS to_assignment_currency,
       ROUND(NVL(cc.conversion_rate, 1), 6)                  AS conversion_rate                       
  FROM (SELECT assignment_continuity_id,
               contractor_person_id,
               hiring_mgr_person_id,
               act_hiring_mgr_person_id,
               buyer_org_id,
               supplier_org_id,
               job_id,
               candidate_id,
               assignment_type,
               amendment_id,
               amendment_in_process_num,
               assignment_start_dt,
               assignment_end_dt,
               assignment_actual_end_dt,
               actual_end_dt_no_deflt,
               last_modified_date,
               assignment_duration,
               assignment_state_id,
               assignment_state,
               approval_state_id,
               approval_state,
               sourcing_method,
               candidate_sourcing_method_id,
               candidate_sourcing_method,
               current_edition_id,
               cac_collection1_id,
               cac_collection2_id,
               contact_info_id,
               address_guid,
               cam_person_id,
               sar_person_id,
               project_id,
               project_agreement_id,
               creator_person_id,
               timecard_approval_workflow_id,
               evaluation_id,
               procurement_wkfl_edition_id,
               assign_requisition_type,
               approval_workflow_id,
               worker_id,
               work_order_id,
               udf_collection_id,
               wov_udf_collection_id,
               worker_ed_udf_collection_id,
               onboard_allowed,
               onboard_checklist_id,
               buyer_resource_id,
               org_sub_classification,
               jc_value,
               jc_type,
               jc_description,
               assign_job_title,
               assign_job_title_lp,
               phase_type_id,
               current_phase,
               assignment_currency_id,
               assignment_currency,
               est_total_budgeted_amount,
               est_wo_budget_remain_approved,
               assignment_end_reason_codes,
               --eval_res_perform_duties_id,
               --eval_res_use_again_id,
               --eval_res_for_another_pos_id,
               --eval_res_perform_duties,
               --eval_res_use_again,
               --eval_res_for_another_pos,
               --rates
               rate_type_id,
               rate_type,
               reg_bill_rate,
               ot_bill_rate AS bill_rate_ot,
               dt_bill_rate AS bill_rate_dt,
               custom_bill_rate AS bill_rate_custom,
               adjusted_bill_rate,
               adjusted_ot_rate AS adjusted_bill_rate_ot,
               adjusted_dt_rate AS adjusted_bill_rate_dt,
               adjusted_custom_rate AS adjusted_bill_rate_custom,
               supplier_reimb_bill_rate,
               supplier_ot_reimb_bill_rate AS supplier_reimb_bill_rate_ot,
               supplier_dt_reimb_bill_rate AS supplier_reimb_bill_rate_dt,
               supplier_cust_reimb_bill_rate AS supplier_reimb_bill_rate_cust,
               reg_pay_rate,
               ot_pay_rate AS pay_rate_ot,
               dt_pay_rate AS pay_rate_dt,
               custom_pay_rate AS pay_rate_custom,
               reg_mark_up,
               ot_mark_up AS mark_up_ot,
               dt_mark_up AS mark_up_dt,
               custom_mark_up AS mark_up_custom               
          FROM lego_assignment_wo
         UNION ALL
        SELECT assignment_continuity_id,
               contractor_person_id,
               hiring_mgr_person_id,
               act_hiring_mgr_person_id,
               buyer_org_id,
               supplier_org_id,
               job_id,
               candidate_id,
               assignment_type,
               NULL AS amendment_id,
               amendment_in_process_num,
               assignment_start_dt,
               assignment_end_dt,
               assignment_actual_end_dt,
               actual_end_dt_no_deflt,
               last_modified_date,
               assignment_duration,
               assignment_state_id,
               assignment_state,
               approval_state_id,
               approval_state,
               sourcing_method,
               candidate_sourcing_method_id,
               candidate_sourcing_method,
               current_edition_id,
               cac_collection1_id,
               cac_collection2_id,
               contact_info_id,
               address_guid,
               cam_person_id,
               sar_person_id,
               project_id,
               project_agreement_id,
               creator_person_id,
               timecard_approval_workflow_id,
               evaluation_id,
               procurement_wkfl_edition_id,
               assign_requisition_type,
               approval_workflow_id,
               worker_id,
               work_order_id,
               udf_collection_id,
               NULL AS wov_udf_collection_id,
               worker_ed_udf_collection_id,
               onboard_allowed,
               onboard_checklist_id,
               buyer_resource_id,
               org_sub_classification,
               jc_value,
               jc_type,
               jc_description,
               assign_job_title,
               assign_job_title_lp,
               phase_type_id,
               current_phase,
               assignment_currency_id,               
               assignment_currency,
               est_total_budgeted_amount,
               est_wo_budget_remain_approved,
               NULL AS assignment_end_reason_codes, --assignment end reason codes do not exist on EA
               --eval_res_perform_duties_id,
               --eval_res_use_again_id,
               --eval_res_for_another_pos_id,
               --eval_res_perform_duties,
               --eval_res_use_again,
               --eval_res_for_another_pos,
               --rates
               rate_type_id,
               rate_type,
               reg_bill_rate,
               ot_bill_rate AS bill_rate_ot,
               dt_bill_rate AS bill_rate_dt,
               custom_bill_rate AS bill_rate_custom,
               adjusted_bill_rate,
               adjusted_ot_rate AS adjusted_bill_rate_ot,
               adjusted_dt_rate AS adjusted_bill_rate_dt,
               adjusted_custom_rate AS adjusted_bill_rate_custom,
               supplier_reimb_bill_rate,
               supplier_ot_reimb_bill_rate AS supplier_reimb_bill_rate_ot,
               supplier_dt_reimb_bill_rate AS supplier_reimb_bill_rate_dt,
               supplier_cust_reimb_bill_rate AS supplier_reimb_bill_rate_cust,
               reg_pay_rate,
               ot_pay_rate AS pay_rate_ot,
               dt_pay_rate AS pay_rate_dt,
               custom_pay_rate AS pay_rate_custom,
               reg_mark_up,
               ot_mark_up AS mark_up_ot,
               dt_mark_up AS mark_up_dt,
               custom_mark_up AS mark_up_custom               
          FROM lego_assignment_ea
         UNION ALL
        SELECT assignment_continuity_id,
               contractor_person_id,
               hiring_mgr_person_id,
               act_hiring_mgr_person_id,
               buyer_org_id,
               supplier_org_id,
               job_id,
               candidate_id,
               assignment_type,
               NULL AS amendment_id,
               amendment_in_process_num,
               assignment_start_dt,
               assignment_end_dt,
               assignment_actual_end_dt,
               actual_end_dt_no_deflt,
               last_modified_date,
               assignment_duration,
               assignment_state_id,
               assignment_state,
               approval_state_id,
               approval_state,
               sourcing_method,
               candidate_sourcing_method_id,
               candidate_sourcing_method,
               current_edition_id,
               cac_collection1_id,
               cac_collection2_id,
               contact_info_id,
               address_guid,
               cam_person_id,
               sar_person_id,
               project_id,
               project_agreement_id,
               creator_person_id,
               timecard_approval_workflow_id,
               evaluation_id,
               procurement_wkfl_edition_id,
               assign_requisition_type,
               approval_workflow_id,
               worker_id,
               work_order_id,
               udf_collection_id,
               NULL AS wov_udf_collection_id,
               worker_ed_udf_collection_id,
               onboard_allowed,
               onboard_checklist_id,
               buyer_resource_id,
               org_sub_classification,
               jc_value,
               jc_type,
               jc_description,
               assign_job_title,
               assign_job_title_lp,
               phase_type_id,
               current_phase,
               assignment_currency_id,               
               assignment_currency,
               est_total_budgeted_amount,
               est_wo_budget_remain_approved,
               NULL AS assignment_end_reason_codes, -- assignment end reason codes do not exist on TA
               --NULL AS eval_res_perform_duties_id,
               --NULL AS eval_res_use_again_id,
               --NULL AS eval_res_for_another_pos_id,
               --NULL AS eval_res_perform_duties,     -- evaluations do not exist on TA
               --NULL AS eval_res_use_again,          -- evaluations do not exist on TA
               --NULL AS eval_res_for_another_pos,    -- evaluations do not exist on TA
               --rates
               NULL  AS rate_type_id,
               'N/A' AS rate_type,
               0     AS reg_bill_rate,
               0     AS bill_rate_ot,
               0     AS bill_rate_dt,
               0     AS bill_rate_custom,
               0     AS adjusted_bill_rate,
               0     AS adjusted_bill_rate_ot,
               0     AS adjusted_bill_rate_dt,
               0     AS adjusted_bill_rate_custom,
               0     AS supplier_reimb_bill_rate,
               0     AS supplier_reimb_bill_rate_ot,
               0     AS supplier_reimb_bill_rate_dt,
               0     AS supplier_reimb_bill_rate_cust,
               0     AS reg_pay_rate,
               0     AS pay_rate_ot,
               0     AS pay_rate_dt,
               0     AS pay_rate_custom,
               0     AS reg_mark_up,
               0     AS mark_up_ot,
               0     AS mark_up_dt,
               0     AS mark_up_custom               
          FROM lego_assignment_ta) assignments,
       lego_currency_conv_rates_vw cc,
       --localized data
       (SELECT constant_value, constant_description
          FROM lego_java_constant_lookup
         WHERE constant_type    = 'SEARCHABLE_ASGNMT_STATE'
           AND locale_fk = (SELECT UPPER(IQN_SESSION_CONTEXT_PKG.get_current_locale_string) FROM dual)) as_jcl,
       /* (SELECT constant_value, constant_description
          FROM lego_java_constant_lookup
         WHERE constant_type    = 'RELOCATION_ASS'
           AND constant_value IN (1,2)
           AND locale_fk = (SELECT UPPER(IQN_SESSION_CONTEXT_PKG.get_current_locale_string) FROM dual)) yesno1_jcl,
       (SELECT constant_value, constant_description
          FROM lego_java_constant_lookup
         WHERE constant_type    = 'RELOCATION_ASS'
           AND constant_value IN (1,2)
           AND locale_fk = (SELECT UPPER(IQN_SESSION_CONTEXT_PKG.get_current_locale_string) FROM dual)) yesno2_jcl,
       (SELECT constant_value, constant_description
          FROM lego_java_constant_lookup
         WHERE constant_type    = 'RELOCATION_ASS'
           AND constant_value IN (1,2)
           AND locale_fk = (SELECT UPPER(IQN_SESSION_CONTEXT_PKG.get_current_locale_string) FROM dual)) yesno3_jcl, */
       (SELECT constant_value, constant_description
          FROM lego_java_constant_lookup
         WHERE constant_type    = 'SOURCING_METHOD'
           AND locale_fk = (SELECT UPPER(IQN_SESSION_CONTEXT_PKG.get_current_locale_string) FROM dual)) csm_jcl,
       (SELECT constant_value, constant_description
          FROM lego_java_constant_lookup
         WHERE constant_type    = 'ASSIGNMENT_PHASE'
           AND locale_fk = (SELECT UPPER(IQN_SESSION_CONTEXT_PKG.get_current_locale_string) FROM dual)) cp_jcl,
       (SELECT constant_value, constant_description
          FROM lego_java_constant_lookup
         WHERE constant_type    = 'ASGNMT_APPROVAL_STATE'
           AND locale_fk = (SELECT UPPER(IQN_SESSION_CONTEXT_PKG.get_current_locale_string) FROM dual)) ass_app_jcl,
       (SELECT constant_value, constant_description
          FROM lego_java_constant_lookup
         WHERE constant_type    = 'JOB_CATEGORY'
           AND locale_fk = (SELECT UPPER(IQN_SESSION_CONTEXT_PKG.get_current_locale_string) FROM dual)) jc_jcl,
       (SELECT domain_object_oid AS jc_value, 
               locale_preference,
               text1 AS assign_jc_description
          FROM localized_text
         WHERE domain_object_class     = 'CustomJobCategory'
           AND domain_object_attribute = 'localizedTexts'
           AND locale_preference       = (SELECT IQN_SESSION_CONTEXT_PKG.get_current_locale_preference FROM dual)) jc_cust,
       (SELECT domain_object_oid AS current_edition_id,
               locale_preference,
               text1 AS assign_job_title
          FROM localized_text
         WHERE domain_object_class     = 'AssignmentEdition'
           AND domain_object_attribute = 'JOB_TITLE'
           AND locale_preference       = (SELECT IQN_SESSION_CONTEXT_PKG.get_current_locale_preference FROM dual)) ass_title_jcl,
       (SELECT constant_value, constant_description
          FROM lego_java_constant_lookup
         WHERE constant_type    = 'RES_RATE_BASIS'
           AND locale_fk = (SELECT UPPER(IQN_SESSION_CONTEXT_PKG.get_current_locale_string) FROM dual)) rate_type_jcl           
 WHERE assignments.assignment_currency_id       = cc.original_currency_id(+)
   AND assignments.assignment_state_id          = as_jcl.constant_value(+)
   AND assignments.candidate_sourcing_method_id = csm_jcl.constant_value(+)
   AND assignments.phase_type_id                = cp_jcl.constant_value(+)
   AND assignments.current_edition_id           = ass_title_jcl.current_edition_id(+)
   AND assignments.approval_state_id            = ass_app_jcl.constant_value(+)
   AND assignments.jc_value                     = jc_jcl.constant_value(+)
   AND assignments.jc_value                     = jc_cust.jc_value(+)
   --AND assignments.eval_res_perform_duties_id   = yesno1_jcl.constant_value(+)
   --AND assignments.eval_res_use_again_id        = yesno2_jcl.constant_value(+)
   --AND assignments.eval_res_for_another_pos_id  = yesno3_jcl.constant_value(+)
   AND assignments.rate_type_id                 = rate_type_jcl.constant_value(+)
/
