CREATE OR REPLACE FORCE VIEW lego_invoice_vw 
AS
SELECT li.invoice_id,
       li.invoice_batch_id,
       li.invoice_adjustment_id,
       li.buyer_org_id,
       li.configuration_edition_id,      
       li.invoice_date,
       li.created_by_person_id, 
       li.last_updated_by_person_id,
       li.invoice_create_date,
       li.bill_through_date,
       li.total_bill_amount,
       ROUND (li.total_bill_amount * NVL(cc.conversion_rate, 1), 2) AS total_bill_amt_cc,
       li.total_fee_amount,
       ROUND (li.total_fee_amount * NVL(cc.conversion_rate, 1), 2) AS total_fee_amt_cc,
       li.total_buyer_adjusted_amount,
       ROUND (li.total_buyer_adjusted_amount * NVL(cc.conversion_rate, 1), 2) AS total_buyer_adjusted_amt_cc,
       li.total_supplier_reimb_amount,
       ROUND (li.total_supplier_reimb_amount * NVL(cc.conversion_rate, 1), 2) AS total_supplier_reimb_amt_cc,
       li.net_buyer_adjusted_amount,
       ROUND (li.net_buyer_adjusted_amount * NVL(cc.conversion_rate, 1), 2) AS net_buyer_adjusted_amt_cc,
       li.net_supplier_reimb_amount,
       ROUND (li.net_supplier_reimb_amount * NVL(cc.conversion_rate, 1), 2) AS net_supplier_reimb_amt_cc,
       li.total_buyer_fee_amount,
       ROUND (li.total_buyer_fee_amount * NVL(cc.conversion_rate, 1), 2) AS total_buyer_fee_amount_cc,
       li.total_supplier_fee_amount,
       ROUND (li.total_supplier_fee_amount * NVL(cc.conversion_rate, 1), 2) AS total_supplier_fee_amt_cc,
       li.total_mgmt_fee_rebate_amount,
       ROUND (li.total_mgmt_fee_rebate_amount * NVL(cc.conversion_rate, 1), 2) AS total_mgmt_fee_rebate_amt_cc,
       li.total_wthldg_tax_on_fee_amount,
       ROUND (li.total_wthldg_tax_on_fee_amount * NVL(cc.conversion_rate, 1), 2) AS total_wthldg_tax_on_fee_amt_cc,
       li.total_mgmt_fee_tax_amount,
       ROUND (li.total_mgmt_fee_tax_amount * NVL(cc.conversion_rate, 1), 2) AS total_mgmt_fee_tax_amt_cc,
       li.total_buyer_tax_amount,
       ROUND (li.total_buyer_tax_amount * NVL(cc.conversion_rate, 1), 2) AS total_buyer_tax_amt_cc,
       li.total_supplier_tax_amount,
       ROUND (li.total_supplier_tax_amount * NVL(cc.conversion_rate, 1), 2) AS total_supplier_tax_amt_cc,
       li.total_buyer_discount_amount,
       ROUND (li.total_buyer_discount_amount * NVL(cc.conversion_rate, 1), 2) AS total_buyer_discount_amt_cc,
       li.total_supplier_discount_amount,
       ROUND (li.total_supplier_discount_amount * NVL(cc.conversion_rate, 1), 2) AS total_supplier_discount_amt_cc,
       li.currency_id,
       li.currency,
       NVL(cc.converted_currency_id, li.currency_id) AS to_inv_currency_id,
       NVL(cc.converted_currency_code, li.currency)  AS to_inv_currency,
       ROUND (NVL(cc.conversion_rate, 1), 6)         AS conversion_rate         
  FROM lego_invoice li,
       lego_currency_conv_rates_vw cc
 WHERE li.currency_id = cc.original_currency_id(+)
/


