CREATE OR REPLACE FORCE VIEW  lego_approvals_vw
AS
   SELECT buyer_org_id,
          approval_buyer_org_id,
          approval_supplier_org_id,
          approvable_id,
          date_submitted_for_app AS sub_for_approval_date,
          date_approved_date approved_date,
          NVL(last_event_date, date_approved_date) AS last_approved_date,
          first_actual_approver_id,
          second_actual_approver_id,
          third_actual_approver_id,
          fourth_actual_approver_id,
          fifth_actual_approver_id,
          sixth_actual_approver_id,
          seventh_actual_approver_id,
          eighth_actual_approver_id,
          first_planned_approver_id,
          second_planned_approver_id,
          third_planned_approver_id,
          fourth_planned_approver_id,
          fifth_planned_approver_id,
          sixth_planned_approver_id,
          seventh_planned_approver_id,
          eighth_planned_approver_id,
          first_actual_approver,
          second_actual_approver,
          third_actual_approver,
          fourth_actual_approver,
          fifth_actual_approver,
          sixth_actual_approver,
          seventh_actual_approver,
          eighth_actual_approver,
          first_planned_approver,
          second_planned_approver,
          third_planned_approver,
          fourth_planned_approver,
          fifth_planned_approver,
          sixth_planned_approver,
          seventh_planned_approver,
          eighth_planned_approver,
          first_actual_primary_email,
          second_actual_primary_email,
          third_actual_primary_email,
          fourth_actual_primary_email,
          fifth_actual_primary_email,
          sixth_actual_primary_email,
          seventh_actual_primary_email,
          eighth_actual_primary_email,
          first_planned_primary_email,
          second_planned_primary_email,
          third_planned_primary_email,
          fourth_planned_primary_email,
          fifth_planned_primary_email,
          sixth_planned_primary_email,
          seventh_planned_primary_email,
          eighth_planned_primary_email,
          current_approver,
          final_approver, 
          CASE
             WHEN approvable_type ='ProjectAgreementVersion'
             THEN 'Project Agreement'
             WHEN approvable_type = 'ProjectRFxVersion'
             THEN 'Project RFx Version'
             WHEN approvable_type = 'Job'
             THEN 'Job Requisition'
             WHEN approvable_type = 'SupplierProjectResourceProposal'
             THEN 'Supplier Project Resource Proposal'
             WHEN approvable_type = 'WorkOrderAmendment'
             THEN 'Work Order Amendment'
             WHEN approvable_type = 'WorkOrderVersion'
             THEN 'Work Order'
             WHEN approvable_type = 'MilestoneInvoice'
             THEN 'Milestone Invoice'
             WHEN approvable_type = 'PaymentRequest'
             THEN 'Payment Request'
             WHEN approvable_type = 'TimeCard'
             THEN 'Timecard'
             WHEN approvable_type = 'AssignmentEdition'
             THEN 'Assignment'
             WHEN approvable_type = 'ExpenseReport'
             THEN 'Expense Report'
             WHEN approvable_type = 'RequestToBuyEdition'
             THEN 'Request To Buy'
             ELSE approvable_type
          END
          AS approval_type,
          approvable_type,
          approval_status,
          id,
          hiring_mgr_person_id,
          approval_buyer_name,
          approval_supp_name,
          last_event,
          last_event_date,
          name_type,
          approval_workflow,
          time_last_approver,
          bo_name,
          contractor_full_name,
          currency_unit,
          current_approver_email,
          date_approved_t_stamp,
          date_sub_for_app_t_stamp,
          time_in_approval_process,
          CASE WHEN Ranking = 1 THEN 'Y' ELSE 'N' END as active_process
     FROM lego_approval la
/

CREATE OR REPLACE FORCE VIEW lego_assignment_approvals_vw 
AS
SELECT buyer_org_id,
          approval_buyer_org_id,
          approval_supplier_org_id,
          assignment_continuity_id,
          approvable_id,
          asm_sub_for_approval_date,
          asm_approved_date,
          asm_last_approved_date,
          asm_first_actual_approver,
          asm_second_actual_approver,
          asm_third_actual_approver,
          asm_fourth_actual_approver,
          asm_fifth_actual_approver,
          asm_sixth_actual_approver,
          asm_seven_actual_approver,
          asm_eighth_actual_approver,
          asm_first_planned_approver,
          asm_second_planned_approver,
          asm_third_planned_approver,
          asm_fourth_planned_approver,
          asm_fifth_planned_approver,
          asm_sixth_planned_approver,
          asm_seven_planned_approver,
          asm_eighth_planned_approver,
          asm_first_actual_pri_email,
          asm_second_actual_pri_email,
          asm_third_actual_pri_email,
          asm_fourth_actual_pri_email,
          asm_fifth_actual_pri_email,
          asm_sixth_actual_pri_email,
          asm_seventh_actual_pri_email,
          asm_eighth_actual_pri_email,
          asm_first_planned_pri_email,
          asm_second_planned_pri_email,
          asm_third_planned_pri_email,
          asm_fourth_planned_pri_email,
          asm_fifth_planned_pri_email,
          asm_sixth_planned_pri_email,
          asm_seventh_planned_pri_email,
          asm_eighth_planned_pri_email,
          asm_current_approver,
          asm_final_approver,
          asm_approval_type,
          asm_approval_status,
          asm_hiring_mgr_person_id,
          asm_approval_buyer_name,
          asm_approval_supp_name,
          asm_last_event,
          asm_last_event_date,
          asm_name_type,
          asm_approval_workflow,
          asm_time_last_approver,
          asm_bo_name,
          asm_contractor_full_name,
          asm_currency_unit,
          asm_current_approver_email,
          asm_date_approved_t_stamp,
          asm_date_sub_for_app_t_stamp,
          asm_time_in_approval_process,
          asm_active_process
FROM (
SELECT buyer_org_id,
          approval_buyer_org_id,
          approval_supplier_org_id,
          TO_NUMBER (ID) AS assignment_continuity_id,
          approvable_id,
          date_submitted_for_app asm_sub_for_approval_date,
          date_approved_date asm_approved_date,
          NVL(last_event_date, date_approved_date) asm_last_approved_date,
          first_actual_approver  asm_first_actual_approver,
          second_actual_approver asm_second_actual_approver,
          third_actual_approver  asm_third_actual_approver,
          fourth_actual_approver asm_fourth_actual_approver,
          fifth_actual_approver asm_fifth_actual_approver,
          sixth_actual_approver asm_sixth_actual_approver,
          seventh_actual_approver asm_seven_actual_approver,
          eighth_actual_approver asm_eighth_actual_approver,
          first_planned_approver asm_first_planned_approver,
          second_planned_approver asm_second_planned_approver,
          third_planned_approver asm_third_planned_approver,
          fourth_planned_approver asm_fourth_planned_approver,
          fifth_planned_approver asm_fifth_planned_approver,
          sixth_planned_approver asm_sixth_planned_approver,
          seventh_planned_approver asm_seven_planned_approver,
          eighth_planned_approver asm_eighth_planned_approver,
          first_actual_primary_email asm_first_actual_pri_email,
          second_actual_primary_email asm_second_actual_pri_email,
          third_actual_primary_email asm_third_actual_pri_email,
          fourth_actual_primary_email asm_fourth_actual_pri_email,
          fifth_actual_primary_email asm_fifth_actual_pri_email,
          sixth_actual_primary_email asm_sixth_actual_pri_email,
          seventh_actual_primary_email asm_seventh_actual_pri_email,
          eighth_actual_primary_email asm_eighth_actual_pri_email,
          first_planned_primary_email asm_first_planned_pri_email,
          second_planned_primary_email asm_second_planned_pri_email,
          third_planned_primary_email asm_third_planned_pri_email,
          fourth_planned_primary_email asm_fourth_planned_pri_email,
          fifth_planned_primary_email asm_fifth_planned_pri_email,
          sixth_planned_primary_email asm_sixth_planned_pri_email,
          seventh_planned_primary_email asm_seventh_planned_pri_email,
          eighth_planned_primary_email asm_eighth_planned_pri_email,
          current_approver asm_current_approver,
          final_approver asm_final_approver,
          CASE
             WHEN approvable_type = 'WorkOrderAmendment'
             THEN 'Work Order Amendment'
             WHEN approvable_type = 'WorkOrderVersion'
             THEN 'Work Order'
             WHEN approvable_type = 'AssignmentEdition'
             THEN 'Assignment'
             ELSE approvable_type
          END
          AS asm_approval_type,
          approval_status asm_approval_status,
          hiring_mgr_person_id asm_hiring_mgr_person_id,
          approval_buyer_name asm_approval_buyer_name,
          approval_supp_name asm_approval_supp_name,
          last_event asm_last_event,
          last_event_date asm_last_event_date,
          name_type asm_name_type,
          approval_workflow asm_approval_workflow,
          time_last_approver asm_time_last_approver,
          bo_name asm_bo_name,
          contractor_full_name asm_contractor_full_name,
          currency_unit asm_currency_unit,
          current_approver_email asm_current_approver_email,
          date_approved_t_stamp asm_date_approved_t_stamp,
          date_sub_for_app_t_stamp asm_date_sub_for_app_t_stamp,
          time_in_approval_process asm_time_in_approval_process,
          'Y' as  asm_active_process
     FROM lego_approval 
    WHERE approvable_type IN ('AssignmentEdition','WorkOrderVersion', 'WorkOrderAmendment')
      AND Ranking = 1
)
/

CREATE OR REPLACE FORCE VIEW lego_workorder_approvals_vw 
AS
SELECT buyer_org_id,
          approval_buyer_org_id,
          approval_supplier_org_id,
          TO_NUMBER (ID)  AS assignment_continuity_id,
          approvable_id wo_version_id, 
          date_submitted_for_app wo_sub_for_approval_date,
          date_approved_date wo_approved_date,
          NVL(last_event_date, date_approved_date) wo_last_approved_date,
          first_actual_approver  wo_first_actual_approver,
          second_actual_approver wo_second_actual_approver,
          third_actual_approver  wo_third_actual_approver,
          fourth_actual_approver wo_fourth_actual_approver,
          fifth_actual_approver wo_fifth_actual_approver,
          sixth_actual_approver wo_sixth_actual_approver,
          seventh_actual_approver wo_seven_actual_approver,
          eighth_actual_approver wo_eighth_actual_approver,
          first_planned_approver wo_first_planned_approver,
          second_planned_approver wo_second_planned_approver,
          third_planned_approver wo_third_planned_approver,
          fourth_planned_approver wo_fourth_planned_approver,
          fifth_planned_approver wo_fifth_planned_approver,
          sixth_planned_approver wo_sixth_planned_approver,
          seventh_planned_approver wo_seven_planned_approver,
          eighth_planned_approver wo_eighth_planned_approver,
          first_actual_primary_email wo_first_actual_pri_email,
          second_actual_primary_email wo_second_actual_pri_email,
          third_actual_primary_email wo_third_actual_pri_email,
          fourth_actual_primary_email wo_fourth_actual_pri_email,
          fifth_actual_primary_email wo_fifth_actual_pri_email,
          sixth_actual_primary_email wo_sixth_actual_pri_email,
          seventh_actual_primary_email wo_seventh_actual_pri_email,
          eighth_actual_primary_email wo_eighth_actual_pri_email,
          first_planned_primary_email wo_first_planned_pri_email,
          second_planned_primary_email wo_second_planned_pri_email,
          third_planned_primary_email wo_third_planned_pri_email,
          fourth_planned_primary_email wo_fourth_planned_pri_email,
          fifth_planned_primary_email wo_fifth_planned_pri_email,
          sixth_planned_primary_email wo_sixth_planned_pri_email,
          seventh_planned_primary_email wo_seventh_planned_pri_email,
          eighth_planned_primary_email wo_eighth_planned_pri_email,
          current_approver wo_current_approver,
          final_approver wo_final_approver,
          CASE
             WHEN approvable_type = 'WorkOrderAmendment'
             THEN 'Work Order Amendment'
             WHEN approvable_type = 'WorkOrderVersion'
             THEN 'Work Order'
             ELSE approvable_type
          END
          AS wo_approval_type,
          approval_status wo_approval_status,
          hiring_mgr_person_id wo_hiring_mgr_person_id,
          approval_buyer_name wo_approval_buyer_name,
          approval_supp_name wo_approval_supp_name,
          last_event wo_last_event,
          last_event_date wo_last_event_date,
          name_type wo_name_type,
          approval_workflow wo_approval_workflow,
          time_last_approver wo_time_last_approver,
          bo_name wo_bo_name,
          contractor_full_name wo_contractor_full_name,
          currency_unit wo_currency_unit,
          current_approver_email wo_current_approver_email,
          date_approved_t_stamp wo_date_approved_t_stamp,
          date_sub_for_app_t_stamp wo_date_sub_for_app_t_stamp,
          time_in_approval_process wo_time_in_approval_process,
          'Y' wo_active_process
     FROM lego_approval 
    WHERE approvable_type IN ('WorkOrderVersion', 'WorkOrderAmendment') 
      AND Ranking = 1
/

CREATE OR REPLACE FORCE VIEW  lego_pa_approvals_vw
AS
   SELECT buyer_org_id,
          approval_buyer_org_id,
          approval_supplier_org_id,
          to_number(ID) pa_id,
          approvable_id pa_version_id,
          date_submitted_for_app pa_sub_for_approval_date,
          date_approved_date pa_approved_date,
	      NVL(last_event_date, date_approved_date) pa_last_approved_date,
          first_actual_approver_id pa_first_actual_approver_id,
          second_actual_approver_id pa_second_actual_approver_id,
          third_actual_approver_id pa_third_actual_approver_id,
          fourth_actual_approver_id pa_fourth_actual_approver_id,
          fifth_actual_approver_id pa_fifth_actual_approver_id,
          sixth_actual_approver_id pa_sixth_actual_approver_id,
          seventh_actual_approver_id pa_seven_actual_approver_id,
          eighth_actual_approver_id pa_eighth_actual_approver_id,
          first_planned_approver_id pa_first_planned_approver_id,
          second_planned_approver_id pa_second_planned_approver_id,
          third_planned_approver_id pa_third_planned_approver_id,
          fourth_planned_approver_id pa_fourth_planned_approver_id,
          fifth_planned_approver_id pa_fifth_planned_approver_id,
          sixth_planned_approver_id pa_sixth_planned_approver_id,
          seventh_planned_approver_id pa_seven_planned_approver_id,
          eighth_planned_approver_id pa_eighth_planned_approver_id,
          first_actual_approver  pa_first_actual_approver,
          second_actual_approver pa_second_actual_approver,
          third_actual_approver  pa_third_actual_approver,
          fourth_actual_approver pa_fourth_actual_approver,
          fifth_actual_approver pa_fifth_actual_approver,
          sixth_actual_approver pa_sixth_actual_approver,
          seventh_actual_approver pa_seven_actual_approver,
          eighth_actual_approver pa_eighth_actual_approver,
          first_planned_approver pa_first_planned_approver,
          second_planned_approver pa_second_planned_approver,
          third_planned_approver pa_third_planned_approver,
          fourth_planned_approver pa_fourth_planned_approver,
          fifth_planned_approver pa_fifth_planned_approver,
          sixth_planned_approver pa_sixth_planned_approver,
          seventh_planned_approver pa_seven_planned_approver,
          eighth_planned_approver pa_eighth_planned_approver,
          first_actual_primary_email PA_first_actual_pri_email,
          second_actual_primary_email PA_second_actual_pri_email,
          third_actual_primary_email PA_third_actual_pri_email,
          fourth_actual_primary_email PA_fourth_actual_pri_email,
          fifth_actual_primary_email PA_fifth_actual_pri_email,
          sixth_actual_primary_email PA_sixth_actual_pri_email,
          seventh_actual_primary_email PA_seventh_actual_pri_email,
          eighth_actual_primary_email PA_eighth_actual_pri_email,
          first_planned_primary_email PA_first_planned_pri_email,
          second_planned_primary_email PA_second_planned_pri_email,
          third_planned_primary_email PA_third_planned_pri_email,
          fourth_planned_primary_email PA_fourth_planned_pri_email,
          fifth_planned_primary_email PA_fifth_planned_pri_email,
          sixth_planned_primary_email PA_sixth_planned_pri_email,
          seventh_planned_primary_email PA_seventh_planned_pri_email,
          eighth_planned_primary_email PA_eighth_planned_pri_email,
          current_approver pa_current_approver,
          final_approver pa_final_approver,
          'Project Agreement' AS pa_approval_type,
          approval_status pa_approval_status,
          hiring_mgr_person_id pa_hiring_mgr_person_id,
          approval_buyer_name pa_approval_buyer_name,
          approval_supp_name pa_approval_supp_name,
          last_event pa_last_event,
          last_event_date pa_last_event_date,
          name_type pa_name_type,
          approval_workflow pa_approval_workflow,
          time_last_approver pa_time_last_approver,
          bo_name pa_bo_name,
          contractor_full_name pa_contractor_full_name,
          currency_unit pa_currency_unit,
          current_approver_email pa_current_approver_email,
          date_approved_t_stamp pa_date_approved_t_stamp,
          date_sub_for_app_t_stamp pa_date_sub_for_app_t_stamp,
          time_in_approval_process pa_time_in_approval_process,
          'Y' pa_active_process
     FROM lego_approval
    WHERE approvable_type = 'ProjectAgreementVersion'
      AND Ranking = 1
/

CREATE OR REPLACE FORCE VIEW lego_expense_approvals_vw
AS
   SELECT buyer_org_id,
          approval_buyer_org_id,
          approval_supplier_org_id,
          approvable_id expense_report_id,
          id expense_report_number,
          date_submitted_for_app exp_sub_for_approval_date,
          date_approved_date exp_approved_date,
	      NVL(last_event_date, date_approved_date) exp_last_approved_date,
          first_actual_approver_id exp_first_actual_approver_id,
          second_actual_approver_id exp_second_actual_approver_id,
          third_actual_approver_id exp_third_actual_approver_id,
          fourth_actual_approver_id exp_fourth_actual_approver_id,
          fifth_actual_approver_id exp_fifth_actual_approver_id,
          sixth_actual_approver_id exp_sixth_actual_approver_id,
          seventh_actual_approver_id exp_seven_actual_approver_id,
          eighth_actual_approver_id exp_eighth_actual_approver_id,
          first_planned_approver_id exp_first_planned_approver_id,
          second_planned_approver_id exp_second_planned_approver_id,
          third_planned_approver_id exp_third_planned_approver_id,
          fourth_planned_approver_id exp_fourth_planned_approver_id,
          fifth_planned_approver_id exp_fifth_planned_approver_id,
          sixth_planned_approver_id exp_sixth_planned_approver_id,
          seventh_planned_approver_id exp_seven_planned_approver_id,
          eighth_planned_approver_id exp_eighth_planned_approver_id,
          first_actual_approver  exp_first_actual_approver,
          second_actual_approver exp_second_actual_approver,
          third_actual_approver  exp_third_actual_approver,
          fourth_actual_approver exp_fourth_actual_approver,
          fifth_actual_approver exp_fifth_actual_approver,
          sixth_actual_approver exp_sixth_actual_approver,
          seventh_actual_approver exp_seven_actual_approver,
          eighth_actual_approver exp_eighth_actual_approver,
          first_planned_approver exp_first_planned_approver,
          second_planned_approver exp_second_planned_approver,
          third_planned_approver exp_third_planned_approver,
          fourth_planned_approver exp_fourth_planned_approver,
          fifth_planned_approver exp_fifth_planned_approver,
          sixth_planned_approver exp_sixth_planned_approver,
          seventh_planned_approver exp_seven_planned_approver,
          eighth_planned_approver exp_eighth_planned_approver,
          first_actual_primary_email exp_first_actual_pri_email,
          second_actual_primary_email exp_second_actual_pri_email,
          third_actual_primary_email exp_third_actual_pri_email,
          fourth_actual_primary_email exp_fourth_actual_pri_email,
          fifth_actual_primary_email exp_fifth_actual_pri_email,
          sixth_actual_primary_email exp_sixth_actual_pri_email,
          seventh_actual_primary_email exp_seventh_actual_pri_email,
          eighth_actual_primary_email exp_eighth_actual_pri_email,
          first_planned_primary_email exp_first_planned_pri_email,
          second_planned_primary_email exp_second_planned_pri_email,
          third_planned_primary_email exp_third_planned_pri_email,
          fourth_planned_primary_email exp_fourth_planned_pri_email,
          fifth_planned_primary_email exp_fifth_planned_pri_email,
          sixth_planned_primary_email exp_sixth_planned_pri_email,
          seventh_planned_primary_email exp_seventh_planned_pri_email,
          eighth_planned_primary_email exp_eighth_planned_pri_email,
          current_approver exp_current_approver,
          final_approver exp_final_approver,
          'Expense Report' AS exp_approval_type,
          approval_status exp_approval_status,
          hiring_mgr_person_id exp_hiring_mgr_person_id,
          approval_buyer_name exp_approval_buyer_name,
          approval_supp_name exp_approval_supp_name,
          last_event exp_last_event,
          last_event_date exp_last_event_date,
          name_type exp_name_type,
          approval_workflow exp_approval_workflow,
          time_last_approver exp_time_last_approver,
          bo_name exp_bo_name,
          contractor_full_name exp_contractor_full_name,
          currency_unit exp_currency_unit,
          current_approver_email exp_current_approver_email,
          date_approved_t_stamp exp_date_approved_t_stamp,
          date_sub_for_app_t_stamp exp_date_sub_for_app_t_stamp,
          time_in_approval_process exp_time_in_approval_process,
          'Y'exp_active_process
     FROM lego_approval
    WHERE approvable_type = 'ExpenseReport'
      AND Ranking = 1
/

CREATE OR REPLACE FORCE VIEW lego_timecard_approvals_vw
AS
   SELECT buyer_org_id,
          approval_buyer_org_id,
          approval_supplier_org_id,
          approvable_id timecard_id,
          id timecard_number,
          date_submitted_for_app tc_sub_for_approval_date,
          date_approved_date tc_approved_date,
	      NVL(last_event_date, date_approved_date) tc_last_approved_date,
          first_actual_approver_id tc_first_actual_approver_id,
          second_actual_approver_id tc_second_actual_approver_id,
          third_actual_approver_id tc_third_actual_approver_id,
          fourth_actual_approver_id tc_fourth_actual_approver_id,
          fifth_actual_approver_id tc_fifth_actual_approver_id,
          sixth_actual_approver_id tc_sixth_actual_approver_id,
          seventh_actual_approver_id tc_seven_actual_approver_id,
          eighth_actual_approver_id tc_eighth_actual_approver_id,
          first_planned_approver_id tc_first_planned_approver_id,
          second_planned_approver_id tc_second_planned_approver_id,
          third_planned_approver_id tc_third_planned_approver_id,
          fourth_planned_approver_id tc_fourth_planned_approver_id,
          fifth_planned_approver_id tc_fifth_planned_approver_id,
          sixth_planned_approver_id tc_sixth_planned_approver_id,
          seventh_planned_approver_id tc_seven_planned_approver_id,
          eighth_planned_approver_id tc_eighth_planned_approver_id,
          first_actual_approver  tc_first_actual_approver,
          second_actual_approver tc_second_actual_approver,
          third_actual_approver  tc_third_actual_approver,
          fourth_actual_approver tc_fourth_actual_approver,
          fifth_actual_approver tc_fifth_actual_approver,
          sixth_actual_approver tc_sixth_actual_approver,
          seventh_actual_approver tc_seven_actual_approver,
          eighth_actual_approver tc_eighth_actual_approver,
          first_planned_approver tc_first_planned_approver,
          second_planned_approver tc_second_planned_approver,
          third_planned_approver tc_third_planned_approver,
          fourth_planned_approver tc_fourth_planned_approver,
          fifth_planned_approver tc_fifth_planned_approver,
          sixth_planned_approver tc_sixth_planned_approver,
          seventh_planned_approver tc_seven_planned_approver,
          eighth_planned_approver tc_eighth_planned_approver,
          first_actual_primary_email tc_first_actual_pri_email,
          second_actual_primary_email tc_second_actual_pri_email,
          third_actual_primary_email tc_third_actual_pri_email,
          fourth_actual_primary_email tc_fourth_actual_pri_email,
          fifth_actual_primary_email tc_fifth_actual_pri_email,
          sixth_actual_primary_email tc_sixth_actual_pri_email,
          seventh_actual_primary_email tc_seventh_actual_pri_email,
          eighth_actual_primary_email tc_eighth_actual_pri_email,
          first_planned_primary_email tc_first_planned_pri_email,
          second_planned_primary_email tc_second_planned_pri_email,
          third_planned_primary_email tc_third_planned_pri_email,
          fourth_planned_primary_email tc_fourth_planned_pri_email,
          fifth_planned_primary_email tc_fifth_planned_pri_email,
          sixth_planned_primary_email tc_sixth_planned_pri_email,
          seventh_planned_primary_email tc_seventh_planned_pri_email,
          eighth_planned_primary_email tc_eighth_planned_pri_email,
          current_approver tc_current_approver,
          final_approver tc_final_approver,
          'Timecard' AS tc_approval_type,
          approval_status tc_approval_status,
          hiring_mgr_person_id tc_hiring_mgr_person_id,
          approval_buyer_name tc_approval_buyer_name,
          approval_supp_name tc_approval_supp_name,
          last_event tc_last_event,
          last_event_date tc_last_event_date,
          name_type tc_name_type,
          approval_workflow tc_approval_workflow,
          time_last_approver tc_time_last_approver,
          bo_name tc_bo_name,
          contractor_full_name tc_contractor_full_name,
          currency_unit tc_currency_unit,
          current_approver_email tc_current_approver_email,
          date_approved_t_stamp tc_date_approved_t_stamp,
          date_sub_for_app_t_stamp tc_date_sub_for_app_t_stamp,
          time_in_approval_process tc_time_in_approval_process,
          'Y' tc_active_process
     FROM lego_approval
    WHERE approvable_type = 'TimeCard'
      AND Ranking = 1
/

CREATE OR REPLACE FORCE VIEW  lego_job_approvals_vw
AS
   SELECT buyer_org_id,
          approval_buyer_org_id,
          approval_supplier_org_id,
          approvable_id job_approvable_id,
          to_number(ID)  job_id,
          date_submitted_for_app job_sub_for_approval_date,
          date_approved_date job_approved_date,
	      NVL(last_event_date, date_approved_date) job_last_approved_date,
          first_actual_approver_id job_first_actual_approver_id,
          second_actual_approver_id job_second_actual_approver_id,
          third_actual_approver_id job_third_actual_approver_id,
          fourth_actual_approver_id job_fourth_actual_approver_id,
          fifth_actual_approver_id job_fifth_actual_approver_id,
          sixth_actual_approver_id job_sixth_actual_approver_id,
          seventh_actual_approver_id job_seven_actual_approver_id,
          eighth_actual_approver_id job_eighth_actual_approver_id,
          first_planned_approver_id job_first_planned_approver_id,
          second_planned_approver_id job_second_planned_approver_id,
          third_planned_approver_id job_third_planned_approver_id,
          fourth_planned_approver_id job_fourth_planned_approver_id,
          fifth_planned_approver_id job_fifth_planned_approver_id,
          sixth_planned_approver_id job_sixth_planned_approver_id,
          seventh_planned_approver_id job_seven_planned_approver_id,
          eighth_planned_approver_id job_eighth_planned_approver_id,
          first_actual_approver  job_first_actual_approver,
          second_actual_approver job_second_actual_approver,
          third_actual_approver  job_third_actual_approver,
          fourth_actual_approver job_fourth_actual_approver,
          fifth_actual_approver job_fifth_actual_approver,
          sixth_actual_approver job_sixth_actual_approver,
          seventh_actual_approver job_seven_actual_approver,
          eighth_actual_approver job_eighth_actual_approver,
          first_planned_approver job_first_planned_approver,
          second_planned_approver job_second_planned_approver,
          third_planned_approver job_third_planned_approver,
          fourth_planned_approver job_fourth_planned_approver,
          fifth_planned_approver job_fifth_planned_approver,
          sixth_planned_approver job_sixth_planned_approver,
          seventh_planned_approver job_seven_planned_approver,
          eighth_planned_approver job_eighth_planned_approver,
          first_actual_primary_email job_first_actual_pri_email,
          second_actual_primary_email job_second_actual_pri_email,
          third_actual_primary_email job_third_actual_pri_email,
          fourth_actual_primary_email job_fourth_actual_pri_email,
          fifth_actual_primary_email job_fifth_actual_pri_email,
          sixth_actual_primary_email job_sixth_actual_pri_email,
          seventh_actual_primary_email job_seventh_actual_pri_email,
          eighth_actual_primary_email job_eighth_actual_pri_email,
          first_planned_primary_email job_first_planned_pri_email,
          second_planned_primary_email job_second_planned_pri_email,
          third_planned_primary_email job_third_planned_pri_email,
          fourth_planned_primary_email job_fourth_planned_pri_email,
          fifth_planned_primary_email job_fifth_planned_pri_email,
          sixth_planned_primary_email job_sixth_planned_pri_email,
          seventh_planned_primary_email job_seventh_planned_pri_email,
          eighth_planned_primary_email job_eighth_planned_pri_email,
          current_approver job_current_approver,
          final_approver job_final_approver,
          'Job Requisition' AS job_approval_type,
          approval_status job_approval_status,
          hiring_mgr_person_id job_hiring_mgr_person_id,
          approval_buyer_name job_approval_buyer_name,
          approval_supp_name job_approval_supp_name,
          last_event job_last_event,
          last_event_date job_last_event_date,
          name_type job_name_type,
          approval_workflow job_approval_workflow,
          time_last_approver job_time_last_approver,
          bo_name job_bo_name,
          contractor_full_name job_owner_full_name,
          currency_unit job_currency_unit,
          current_approver_email job_current_approver_email,
          date_approved_t_stamp job_date_approved_t_stamp,
          date_sub_for_app_t_stamp job_date_sub_for_app_t_stamp,
          time_in_approval_process job_time_in_approval_process,
          'Y' job_active_process
     FROM lego_approval
    WHERE approvable_type = 'Job'
      and ranking = 1
/

CREATE OR REPLACE FORCE VIEW  lego_project_rfx_approvals_vw
AS
   SELECT buyer_org_id,
          approval_buyer_org_id,
          approval_supplier_org_id,
          approvable_id project_rfx_version_id,
          to_number(ID)  project_rfx_id,
          date_submitted_for_app rfx_sub_for_approval_date,
          date_approved_date rfx_approved_date,
	      NVL(last_event_date, date_approved_date) rfx_last_approved_date,
          first_actual_approver_id rfx_first_actual_approver_id,
          second_actual_approver_id rfx_second_actual_approver_id,
          third_actual_approver_id rfx_third_actual_approver_id,
          fourth_actual_approver_id rfx_fourth_actual_approver_id,
          fifth_actual_approver_id rfx_fifth_actual_approver_id,
          sixth_actual_approver_id rfx_sixth_actual_approver_id,
          seventh_actual_approver_id rfx_seven_actual_approver_id,
          eighth_actual_approver_id rfx_eighth_actual_approver_id,
          first_planned_approver_id rfx_first_planned_approver_id,
          second_planned_approver_id rfx_second_planned_approver_id,
          third_planned_approver_id rfx_third_planned_approver_id,
          fourth_planned_approver_id rfx_fourth_planned_approver_id,
          fifth_planned_approver_id rfx_fifth_planned_approver_id,
          sixth_planned_approver_id rfx_sixth_planned_approver_id,
          seventh_planned_approver_id rfx_seven_planned_approver_id,
          eighth_planned_approver_id rfx_eighth_planned_approver_id,
          first_actual_approver  rfx_first_actual_approver,
          second_actual_approver rfx_second_actual_approver,
          third_actual_approver  rfx_third_actual_approver,
          fourth_actual_approver rfx_fourth_actual_approver,
          fifth_actual_approver rfx_fifth_actual_approver,
          sixth_actual_approver rfx_sixth_actual_approver,
          seventh_actual_approver rfx_seven_actual_approver,
          eighth_actual_approver rfx_eighth_actual_approver,
          first_planned_approver rfx_first_planned_approver,
          second_planned_approver rfx_second_planned_approver,
          third_planned_approver rfx_third_planned_approver,
          fourth_planned_approver rfx_fourth_planned_approver,
          fifth_planned_approver rfx_fifth_planned_approver,
          sixth_planned_approver rfx_sixth_planned_approver,
          seventh_planned_approver rfx_seven_planned_approver,
          eighth_planned_approver rfx_eighth_planned_approver,
          first_actual_primary_email rfx_first_actual_pri_email,
          second_actual_primary_email rfx_second_actual_pri_email,
          third_actual_primary_email rfx_third_actual_pri_email,
          fourth_actual_primary_email rfx_fourth_actual_pri_email,
          fifth_actual_primary_email rfx_fifth_actual_pri_email,
          sixth_actual_primary_email rfx_sixth_actual_pri_email,
          seventh_actual_primary_email rfx_seventh_actual_pri_email,
          eighth_actual_primary_email rfx_eighth_actual_pri_email,
          first_planned_primary_email rfx_first_planned_pri_email,
          second_planned_primary_email rfx_second_planned_pri_email,
          third_planned_primary_email rfx_third_planned_pri_email,
          fourth_planned_primary_email rfx_fourth_planned_pri_email,
          fifth_planned_primary_email rfx_fifth_planned_pri_email,
          sixth_planned_primary_email rfx_sixth_planned_pri_email,
          seventh_planned_primary_email rfx_seventh_planned_pri_email,
          eighth_planned_primary_email rfx_eighth_planned_pri_email,
          current_approver rfx_current_approver,
          final_approver rfx_final_approver,
          'Project RFx Version' AS rfx_approval_type,
          approval_status rfx_approval_status,
          hiring_mgr_person_id rfx_hiring_mgr_person_id,
          approval_buyer_name rfx_approval_buyer_name,
          approval_supp_name rfx_approval_supp_name,
          last_event rfx_last_event,
          last_event_date rfx_last_event_date,
          name_type rfx_name_type,
          approval_workflow rfx_approval_workflow,
          time_last_approver rfx_time_last_approver,
          bo_name rfx_bo_name,
          contractor_full_name rfx_contractor_full_name,
          currency_unit rfx_currency_unit,
          current_approver_email rfx_current_approver_email,
          date_approved_t_stamp rfx_date_approved_t_stamp,
          date_sub_for_app_t_stamp rfx_date_sub_for_app_t_stamp,
          time_in_approval_process rfx_time_in_approval_process,
          'Y' rfx_active_process
     FROM lego_approval
    WHERE approvable_type IN ('ProjectRFxVersion', 'Project RFx')
      AND Ranking = 1
/

CREATE OR REPLACE FORCE VIEW lego_mi_approvals_vw
AS
   SELECT buyer_org_id,
          approval_buyer_org_id,
          approval_supplier_org_id,
          approvable_id mi_identifier,
          to_number(ID) mi_id,
          date_submitted_for_app mi_sub_for_approval_date,
          date_approved_date mi_approved_date,
	      NVL(last_event_date, date_approved_date) mi_last_approved_date,
          first_actual_approver_id mi_first_actual_approver_id,
          second_actual_approver_id mi_second_actual_approver_id,
          third_actual_approver_id mi_third_actual_approver_id,
          fourth_actual_approver_id mi_fourth_actual_approver_id,
          fifth_actual_approver_id mi_fifth_actual_approver_id,
          sixth_actual_approver_id mi_sixth_actual_approver_id,
          seventh_actual_approver_id mi_seven_actual_approver_id,
          eighth_actual_approver_id mi_eighth_actual_approver_id,
          first_planned_approver_id mi_first_planned_approver_id,
          second_planned_approver_id mi_second_planned_approver_id,
          third_planned_approver_id mi_third_planned_approver_id,
          fourth_planned_approver_id mi_fourth_planned_approver_id,
          fifth_planned_approver_id mi_fifth_planned_approver_id,
          sixth_planned_approver_id mi_sixth_planned_approver_id,
          seventh_planned_approver_id mi_seven_planned_approver_id,
          eighth_planned_approver_id mi_eighth_planned_approver_id,
          first_actual_approver  mi_first_actual_approver,
          second_actual_approver mi_second_actual_approver,
          third_actual_approver  mi_third_actual_approver,
          fourth_actual_approver mi_fourth_actual_approver,
          fifth_actual_approver mi_fifth_actual_approver,
          sixth_actual_approver mi_sixth_actual_approver,
          seventh_actual_approver mi_seven_actual_approver,
          eighth_actual_approver mi_eighth_actual_approver,
          first_planned_approver mi_first_planned_approver,
          second_planned_approver mi_second_planned_approver,
          third_planned_approver mi_third_planned_approver,
          fourth_planned_approver mi_fourth_planned_approver,
          fifth_planned_approver mi_fifth_planned_approver,
          sixth_planned_approver mi_sixth_planned_approver,
          seventh_planned_approver mi_seven_planned_approver,
          eighth_planned_approver mi_eighth_planned_approver,
          first_actual_primary_email mi_first_actual_pri_email,
          second_actual_primary_email mi_second_actual_pri_email,
          third_actual_primary_email mi_third_actual_pri_email,
          fourth_actual_primary_email mi_fourth_actual_pri_email,
          fifth_actual_primary_email mi_fifth_actual_pri_email,
          sixth_actual_primary_email mi_sixth_actual_pri_email,
          seventh_actual_primary_email mi_seventh_actual_pri_email,
          eighth_actual_primary_email mi_eighth_actual_pri_email,
          first_planned_primary_email mi_first_planned_pri_email,
          second_planned_primary_email mi_second_planned_pri_email,
          third_planned_primary_email mi_third_planned_pri_email,
          fourth_planned_primary_email mi_fourth_planned_pri_email,
          fifth_planned_primary_email mi_fifth_planned_pri_email,
          sixth_planned_primary_email mi_sixth_planned_pri_email,
          seventh_planned_primary_email mi_seventh_planned_pri_email,
          eighth_planned_primary_email mi_eighth_planned_pri_email,
          current_approver mi_current_approver,
          final_approver mi_final_approver,
          'Milestone Invoice' AS mi_approval_type,
          approval_status mi_approval_status,
          hiring_mgr_person_id mi_hiring_mgr_person_id,
          approval_buyer_name mi_approval_buyer_name,
          approval_supp_name mi_approval_supp_name,
          last_event mi_last_event,
          last_event_date mi_last_event_date,
          name_type mi_name_type,
          approval_workflow mi_approval_workflow,
          time_last_approver mi_time_last_approver,
          bo_name mi_bo_name,
          contractor_full_name mi_contractor_full_name,
          currency_unit mi_currency_unit,
          current_approver_email mi_current_approver_email,
          date_approved_t_stamp mi_date_approved_t_stamp,
          date_sub_for_app_t_stamp mi_date_sub_for_app_t_stamp,
          time_in_approval_process mi_time_in_approval_process,
          'Y' mi_active_process
     FROM lego_approval
    WHERE approvable_type = 'MilestoneInvoice'
      AND Ranking = 1
/

CREATE OR REPLACE FORCE VIEW  lego_pr_approvals_vw
AS
   SELECT buyer_org_id,
          approval_buyer_org_id,
          approval_supplier_org_id,
          approvable_id pr_approvable_id,
          to_number(ID) pr_id,
          date_submitted_for_app pr_sub_for_approval_date,
          date_approved_date pr_approved_date,
	      NVL(last_event_date, date_approved_date) pr_last_approved_date,
          first_actual_approver_id pr_first_actual_approver_id,
          second_actual_approver_id pr_second_actual_approver_id,
          third_actual_approver_id pr_third_actual_approver_id,
          fourth_actual_approver_id pr_fourth_actual_approver_id,
          fifth_actual_approver_id pr_fifth_actual_approver_id,
          sixth_actual_approver_id pr_sixth_actual_approver_id,
          seventh_actual_approver_id pr_seven_actual_approver_id,
          eighth_actual_approver_id pr_eighth_actual_approver_id,
          first_planned_approver_id pr_first_planned_approver_id,
          second_planned_approver_id pr_second_planned_approver_id,
          third_planned_approver_id pr_third_planned_approver_id,
          fourth_planned_approver_id pr_fourth_planned_approver_id,
          fifth_planned_approver_id pr_fifth_planned_approver_id,
          sixth_planned_approver_id pr_sixth_planned_approver_id,
          seventh_planned_approver_id pr_seven_planned_approver_id,
          eighth_planned_approver_id pr_eighth_planned_approver_id,
          first_actual_approver  pr_first_actual_approver,
          second_actual_approver pr_second_actual_approver,
          third_actual_approver  pr_third_actual_approver,
          fourth_actual_approver pr_fourth_actual_approver,
          fifth_actual_approver pr_fifth_actual_approver,
          sixth_actual_approver pr_sixth_actual_approver,
          seventh_actual_approver pr_seven_actual_approver,
          eighth_actual_approver pr_eighth_actual_approver,
          first_planned_approver pr_first_planned_approver,
          second_planned_approver pr_second_planned_approver,
          third_planned_approver pr_third_planned_approver,
          fourth_planned_approver pr_fourth_planned_approver,
          fifth_planned_approver pr_fifth_planned_approver,
          sixth_planned_approver pr_sixth_planned_approver,
          seventh_planned_approver pr_seven_planned_approver,
          eighth_planned_approver pr_eighth_planned_approver,
          first_actual_primary_email pr_first_actual_pri_email,
          second_actual_primary_email pr_second_actual_pri_email,
          third_actual_primary_email pr_third_actual_pri_email,
          fourth_actual_primary_email pr_fourth_actual_pri_email,
          fifth_actual_primary_email pr_fifth_actual_pri_email,
          sixth_actual_primary_email pr_sixth_actual_pri_email,
          seventh_actual_primary_email pr_seventh_actual_pri_email,
          eighth_actual_primary_email pr_eighth_actual_pri_email,
          first_planned_primary_email pr_first_planned_pri_email,
          second_planned_primary_email pr_second_planned_pri_email,
          third_planned_primary_email pr_third_planned_pri_email,
          fourth_planned_primary_email pr_fourth_planned_pri_email,
          fifth_planned_primary_email pr_fifth_planned_pri_email,
          sixth_planned_primary_email pr_sixth_planned_pri_email,
          seventh_planned_primary_email pr_seventh_planned_pri_email,
          eighth_planned_primary_email pr_eighth_planned_pri_email,
          current_approver pr_current_approver,
          final_approver pr_final_approver,
          'Payment Request' AS pr_approval_type,
          approval_status pr_approval_status,
          hiring_mgr_person_id pr_hiring_mgr_person_id,
          approval_buyer_name pr_approval_buyer_name,
          approval_supp_name pr_approval_supp_name,
          last_event pr_last_event,
          last_event_date pr_last_event_date,
          name_type pr_name_type,
          approval_workflow pr_approval_workflow,
          time_last_approver pr_time_last_approver,
          bo_name pr_bo_name,
          contractor_full_name pr_contractor_full_name,
          currency_unit pr_currency_unit,
          current_approver_email pr_current_approver_email,
          date_approved_t_stamp pr_date_approved_t_stamp,
          date_sub_for_app_t_stamp pr_date_sub_for_app_t_stamp,
          time_in_approval_process pr_time_in_approval_process,
          'Y' pr_active_process
     FROM lego_approval 
    WHERE approvable_type = 'PaymentRequest'
      AND Ranking = 1
/

CREATE OR REPLACE FORCE VIEW  lego_req_to_buy_approvals_vw
AS
   SELECT buyer_org_id,
          approval_buyer_org_id,
          approval_supplier_org_id,
          approvable_id request_to_buy_edition_id,
          to_number(ID) request_to_buy_continuity_id,
          date_submitted_for_app rtb_sub_for_approval_date,
          date_approved_date rtb_approved_date,
	      NVL(last_event_date, date_approved_date) rtb_last_approved_date,
          first_actual_approver_id rtb_first_actual_approver_id,
          second_actual_approver_id rtb_second_actual_approver_id,
          third_actual_approver_id rtb_third_actual_approver_id,
          fourth_actual_approver_id rtb_fourth_actual_approver_id,
          fifth_actual_approver_id rtb_fifth_actual_approver_id,
          sixth_actual_approver_id rtb_sixth_actual_approver_id,
          seventh_actual_approver_id rtb_seven_actual_approver_id,
          eighth_actual_approver_id rtb_eighth_actual_approver_id,
          first_planned_approver_id rtb_first_planned_approver_id,
          second_planned_approver_id rtb_second_planned_approver_id,
          third_planned_approver_id rtb_third_planned_approver_id,
          fourth_planned_approver_id rtb_fourth_planned_approver_id,
          fifth_planned_approver_id rtb_fifth_planned_approver_id,
          sixth_planned_approver_id rtb_sixth_planned_approver_id,
          seventh_planned_approver_id rtb_seven_planned_approver_id,
          eighth_planned_approver_id rtb_eighth_planned_approver_id,
          first_actual_approver  rtb_first_actual_approver,
          second_actual_approver rtb_second_actual_approver,
          third_actual_approver  rtb_third_actual_approver,
          fourth_actual_approver rtb_fourth_actual_approver,
          fifth_actual_approver rtb_fifth_actual_approver,
          sixth_actual_approver rtb_sixth_actual_approver,
          seventh_actual_approver rtb_seven_actual_approver,
          eighth_actual_approver rtb_eighth_actual_approver,
          first_planned_approver rtb_first_planned_approver,
          second_planned_approver rtb_second_planned_approver,
          third_planned_approver rtb_third_planned_approver,
          fourth_planned_approver rtb_fourth_planned_approver,
          fifth_planned_approver rtb_fifth_planned_approver,
          sixth_planned_approver rtb_sixth_planned_approver,
          seventh_planned_approver rtb_seven_planned_approver,
          eighth_planned_approver rtb_eighth_planned_approver,
          first_actual_primary_email rtb_first_actual_pri_email,
          second_actual_primary_email rtb_second_actual_pri_email,
          third_actual_primary_email rtb_third_actual_pri_email,
          fourth_actual_primary_email rtb_fourth_actual_pri_email,
          fifth_actual_primary_email rtb_fifth_actual_pri_email,
          sixth_actual_primary_email rtb_sixth_actual_pri_email,
          seventh_actual_primary_email rtb_seventh_actual_pri_email,
          eighth_actual_primary_email rtb_eighth_actual_pri_email,
          first_planned_primary_email rtb_first_planned_pri_email,
          second_planned_primary_email rtb_second_planned_pri_email,
          third_planned_primary_email rtb_third_planned_pri_email,
          fourth_planned_primary_email rtb_fourth_planned_pri_email,
          fifth_planned_primary_email rtb_fifth_planned_pri_email,
          sixth_planned_primary_email rtb_sixth_planned_pri_email,
          seventh_planned_primary_email rtb_seventh_planned_pri_email,
          eighth_planned_primary_email rtb_eighth_planned_pri_email,
          current_approver rtb_current_approver,
          final_approver rtb_final_approver,
          'Request To Buy' AS rtb_approval_type,
          approval_status rtb_approval_status,
          hiring_mgr_person_id rtb_hiring_mgr_person_id,
          approval_buyer_name rtb_approval_buyer_name,
          approval_supp_name rtb_approval_supp_name,
          last_event rtb_last_event,
          last_event_date rtb_last_event_date,
          name_type rtb_name_type,
          approval_workflow rtb_approval_workflow,
          time_last_approver rtb_time_last_approver,
          bo_name rtb_bo_name,
          contractor_full_name rtb_contractor_full_name,
          currency_unit rtb_currency_unit,
          current_approver_email rtb_current_approver_email,
          date_approved_t_stamp rtb_date_approved_t_stamp,
          date_sub_for_app_t_stamp rtb_date_sub_for_app_t_stamp,
          time_in_approval_process rtb_time_in_approval_process,
          'Y' rtb_active_process
     FROM lego_approval
    WHERE approvable_type = 'RequestToBuyEdition'
      AND Ranking = 1
/

CREATE OR REPLACE FORCE VIEW lego_p_res_prop_approvals_vw
AS
   SELECT buyer_org_id,
          approval_buyer_org_id,
          approval_supplier_org_id,
          approvable_id project_resource_proposal_id,
          to_number(ID) prp_id,
          date_submitted_for_app prp_sub_for_approval_date,
          date_approved_date prp_approved_date,
	      NVL(last_event_date, date_approved_date) prp_last_approved_date,
          first_actual_approver_id prp_first_actual_approver_id,
          second_actual_approver_id prp_second_actual_approver_id,
          third_actual_approver_id prp_third_actual_approver_id,
          fourth_actual_approver_id prp_fourth_actual_approver_id,
          fifth_actual_approver_id prp_fifth_actual_approver_id,
          sixth_actual_approver_id prp_sixth_actual_approver_id,
          seventh_actual_approver_id prp_seven_actual_approver_id,
          eighth_actual_approver_id prp_eighth_actual_approver_id,
          first_planned_approver_id prp_first_planned_approver_id,
          second_planned_approver_id prp_second_planned_approver_id,
          third_planned_approver_id prp_third_planned_approver_id,
          fourth_planned_approver_id prp_fourth_planned_approver_id,
          fifth_planned_approver_id prp_fifth_planned_approver_id,
          sixth_planned_approver_id prp_sixth_planned_approver_id,
          seventh_planned_approver_id prp_seven_planned_approver_id,
          eighth_planned_approver_id prp_eighth_planned_approver_id,
          first_actual_approver  prp_first_actual_approver,
          second_actual_approver prp_second_actual_approver,
          third_actual_approver  prp_third_actual_approver,
          fourth_actual_approver prp_fourth_actual_approver,
          fifth_actual_approver prp_fifth_actual_approver,
          sixth_actual_approver prp_sixth_actual_approver,
          seventh_actual_approver prp_seven_actual_approver,
          eighth_actual_approver prp_eighth_actual_approver,
          first_planned_approver prp_first_planned_approver,
          second_planned_approver prp_second_planned_approver,
          third_planned_approver prp_third_planned_approver,
          fourth_planned_approver prp_fourth_planned_approver,
          fifth_planned_approver prp_fifth_planned_approver,
          sixth_planned_approver prp_sixth_planned_approver,
          seventh_planned_approver prp_seven_planned_approver,
          eighth_planned_approver prp_eighth_planned_approver,
          first_actual_primary_email prp_first_actual_pri_email,
          second_actual_primary_email prp_second_actual_pri_email,
          third_actual_primary_email prp_third_actual_pri_email,
          fourth_actual_primary_email prp_fourth_actual_pri_email,
          fifth_actual_primary_email prp_fifth_actual_pri_email,
          sixth_actual_primary_email prp_sixth_actual_pri_email,
          seventh_actual_primary_email prp_seventh_actual_pri_email,
          eighth_actual_primary_email prp_eighth_actual_pri_email,
          first_planned_primary_email prp_first_planned_pri_email,
          second_planned_primary_email prp_second_planned_pri_email,
          third_planned_primary_email prp_third_planned_pri_email,
          fourth_planned_primary_email prp_fourth_planned_pri_email,
          fifth_planned_primary_email prp_fifth_planned_pri_email,
          sixth_planned_primary_email prp_sixth_planned_pri_email,
          seventh_planned_primary_email prp_seventh_planned_pri_email,
          eighth_planned_primary_email prp_eighth_planned_pri_email,
          current_approver prp_current_approver,
          final_approver prp_final_approver,
          'Supplier Project Resource Proposal' AS prp_approval_type,
          approval_status prp_approval_status,
          hiring_mgr_person_id prp_hiring_mgr_person_id,
          approval_buyer_name prp_approval_buyer_name,
          approval_supp_name prp_approval_supp_name,
          last_event prp_last_event,
          last_event_date prp_last_event_date,
          name_type prp_name_type,
          approval_workflow prp_approval_workflow,
          time_last_approver prp_time_last_approver,
          bo_name prp_bo_name,
          contractor_full_name prp_contractor_full_name,
          currency_unit prp_currency_unit,
          current_approver_email prp_current_approver_email,
          date_approved_t_stamp prp_date_approved_t_stamp,
          date_sub_for_app_t_stamp prp_date_sub_for_app_t_stamp,
          time_in_approval_process prp_time_in_approval_process,
          'Y' prp_active_process
     FROM lego_approval
    WHERE approvable_type = 'SupplierProjectResourceProposal'
      AND Ranking = 1
/
