CREATE OR REPLACE FORCE VIEW lego_project_vw
AS
SELECT p.project_id,
       p.buyer_org_id,
       p.supplier_org_id,
       p.org_sub_classification,
       p.cac_collection1_id,
       p.cac_collection2_id,
       p.udf_collection_id,
       p.project_manager_person_id,
       p.project_internal_identifier,
       p.project_title,
       p.project_description,
       p.project_create_date,
       p.estimated_budget_max,
       ROUND (p.estimated_budget_max * NVL(cc.conversion_rate, 1), 2) AS estimated_budget_max_cc,
       p.estimated_budget_min,
       ROUND (p.estimated_budget_min * NVL(cc.conversion_rate, 1), 2) AS estimated_budget_min_cc,
       p.is_archived,
       p.last_modified_date,
       p.project_currency_id, 
       p.project_currency,
       NVL(cc.converted_currency_id, p.project_currency_id) AS to_project_currency_id,
       NVL(cc.converted_currency_code, p.project_currency) AS to_project_currency,
       ROUND (NVL(cc.conversion_rate, 1), 6) AS conversion_rate
  FROM lego_project p,
       lego_currency_conv_rates_vw cc
 WHERE p.project_currency_id = cc.original_currency_id(+)
/
 
CREATE OR REPLACE FORCE VIEW lego_project_cac_vw
    AS 
SELECT project_id,
       cac_collection_id,
       cac_id,
       buyer_org_id,
       cac_kind,
       cac_start_date,
       cac_end_date,
       cac1_segment_1_value,
       cac1_segment_2_value,
       cac1_segment_3_value,
       cac1_segment_4_value,
       cac1_segment_5_value,
       cac1_segment_1_desc,
       cac1_segment_2_desc,
       cac1_segment_3_desc,
       cac1_segment_4_desc,
       cac1_segment_5_desc,
       cac2_segment_1_value,
       cac2_segment_2_value,
       cac2_segment_3_value,
       cac2_segment_4_value,
       cac2_segment_5_value,
       cac2_segment_1_desc,
       cac2_segment_2_desc,
       cac2_segment_3_desc,
       cac2_segment_4_desc,
       cac2_segment_5_desc
  FROM (       
SELECT lpc.project_id,
       lpc.cac_collection_id,
       lpc.cac_id,
       lpc.buyer_org_id,
       lpc.cac_kind,
       lpc.cac_start_date,
       lpc.cac_end_date,
       lc.cac_segment_1_value  AS cac1_segment_1_value,
       lc.cac_segment_2_value  AS cac1_segment_2_value,
       lc.cac_segment_3_value  AS cac1_segment_3_value,
       lc.cac_segment_4_value  AS cac1_segment_4_value,
       lc.cac_segment_5_value  AS cac1_segment_5_value,
       lc.cac_segment_1_desc   AS cac1_segment_1_desc,
       lc.cac_segment_2_desc   AS cac1_segment_2_desc,
       lc.cac_segment_3_desc   AS cac1_segment_3_desc,
       lc.cac_segment_4_desc   AS cac1_segment_4_desc,
       lc.cac_segment_5_desc   AS cac1_segment_5_desc,
       NULL                    AS cac2_segment_1_value,
       NULL                    AS cac2_segment_2_value,
       NULL                    AS cac2_segment_3_value,
       NULL                    AS cac2_segment_4_value,
       NULL                    AS cac2_segment_5_value,
       NULL                    AS cac2_segment_1_desc,
       NULL                    AS cac2_segment_2_desc,
       NULL                    AS cac2_segment_3_desc,
       NULL                    AS cac2_segment_4_desc,
       NULL                    AS cac2_segment_5_desc
  FROM lego_project_cac lpc, 
       lego_cac lc
 WHERE lpc.cac_guid = lc.cac_guid
   AND lpc.cac_kind = 1
 UNION ALL
SELECT lpc.project_id,
       lpc.cac_collection_id,
       lpc.cac_id,
       lpc.buyer_org_id,
       lpc.cac_kind,
       lpc.cac_start_date,
       lpc.cac_end_date,
       NULL                    AS cac1_segment_1_value,
       NULL                    AS cac1_segment_2_value,
       NULL                    AS cac1_segment_3_value,
       NULL                    AS cac1_segment_4_value,
       NULL                    AS cac1_segment_5_value,
       NULL                    AS cac1_segment_1_desc,
       NULL                    AS cac1_segment_2_desc,
       NULL                    AS cac1_segment_3_desc,
       NULL                    AS cac1_segment_4_desc,
       NULL                    AS cac1_segment_5_desc,
       lc.cac_segment_1_value  AS cac2_segment_1_value,
       lc.cac_segment_2_value  AS cac2_segment_2_value,
       lc.cac_segment_3_value  AS cac2_segment_3_value,
       lc.cac_segment_4_value  AS cac2_segment_4_value,
       lc.cac_segment_5_value  AS cac2_segment_5_value,
       lc.cac_segment_1_desc   AS cac2_segment_1_desc,
       lc.cac_segment_2_desc   AS cac2_segment_2_desc,
       lc.cac_segment_3_desc   AS cac2_segment_3_desc,
       lc.cac_segment_4_desc   AS cac2_segment_4_desc,
       lc.cac_segment_5_desc   AS cac2_segment_5_desc
  FROM lego_project_cac lpc, 
       lego_cac lc
 WHERE lpc.cac_guid = lc.cac_guid
   AND lpc.cac_kind = 2)
/


