CREATE OR REPLACE VIEW lego_all_assignment_types_vw
AS
   SELECT ASSIGNMENT_CONTINUITY_ID,
          CONTRACTOR_PERSON_ID,
          HIRING_MGR_PERSON_ID,
          ACT_HIRING_MGR_PERSON_ID,
          BUYER_ORG_ID,
          SUPPLIER_ORG_ID,
          JOB_ID,
          CANDIDATE_ID,
          OFFER_ID,
          ASSIGNMENT_TYPE,
          AMENDMENT_ID,
          AMENDMENT_IN_PROCESS_NUM,
          ASSIGNMENT_CREATE_DATE,
          ASSIGNMENT_START_DT,
          ASSIGNMENT_END_DT,
          ASSIGNMENT_ACTUAL_END_DT,
          ACTUAL_END_DT_NO_DEFLT,
          RELEASED_TO_SUPPLIER_DATE,
          ACCEPTED_BY_SUPPLIER_DATE,
          ASSIGNMENT_EFFECTIVE_DATE,
          LAST_MODIFIED_DATE,
          ASSIGNMENT_DURATION,
          HAS_EVER_BEEN_EFFECTIVE,
          APPROVAL_STATE_ID,
          ASSIGNMENT_STATE_ID,
          APPROVAL_STATE,
          SOURCING_METHOD,
          CANDIDATE_SOURCING_METHOD_ID,
          CURRENT_EDITION_ID,
          CONTACT_INFO_ID,
          CAM_PERSON_ID,
          SAR_PERSON_ID,
          PROJECT_ID,
          PROJECT_AGREEMENT_ID,
          CREATOR_PERSON_ID,
          TIMECARD_APPROVAL_WORKFLOW_ID,
          EVALUATION_ID,
          PROCUREMENT_WKFL_EDITION_ID,
          ASSIGN_REQUISITION_TYPE,
          APPROVAL_WORKFLOW_ID,
          WORKER_ID,
          WORK_ORDER_ID,
          UDF_COLLECTION_ID,
          WOV_UDF_COLLECTION_ID,
          WORKER_ED_UDF_COLLECTION_ID,
          ONBOARD_ALLOWED,
          ONBOARD_CHECKLIST_ID,
          BUYER_RESOURCE_ID,
          SUPPLIER_RESOURCE_ID,
          ORG_SUB_CLASSIFICATION,
          JC_VALUE,
          JC_TYPE,
          JC_DESCRIPTION,
          JL_VALUE,
          JL_DESCRIPTION,
          ASSIGN_JOB_TITLE,
          ASSIGN_JOB_TITLE_LP,
          WAT_DESCRIPTION,
          CURRENT_PHASE_TYPE_ID,
          RATE_TYPE_ID,
          RATE_TYPE,
          REG_BILL_RATE,
          OT_BILL_RATE,
          DT_BILL_RATE,
          CUSTOM_BILL_RATE,
          ADJUSTED_BILL_RATE,
          ADJUSTED_OT_RATE,
          ADJUSTED_DT_RATE,
          ADJUSTED_CUSTOM_RATE,
          SUPPLIER_REIMB_BILL_RATE,
          SUPPLIER_OT_REIMB_BILL_RATE,
          SUPPLIER_DT_REIMB_BILL_RATE,
          SUPPLIER_CUST_REIMB_BILL_RATE,
          REG_PAY_RATE,
          OT_PAY_RATE,
          DT_PAY_RATE,
          CUSTOM_PAY_RATE,
          REG_MARK_UP,
          OT_MARK_UP,
          DT_MARK_UP,
          CUSTOM_MARK_UP,
          ASSIGNMENT_CURRENCY_ID,
          ASSIGNMENT_CURRENCY,
          EST_TOTAL_BUDGETED_AMOUNT
     FROM assignment_wo_iqp
   UNION ALL
   SELECT ASSIGNMENT_CONTINUITY_ID,
          CONTRACTOR_PERSON_ID,
          HIRING_MGR_PERSON_ID,
          ACT_HIRING_MGR_PERSON_ID,
          BUYER_ORG_ID,
          SUPPLIER_ORG_ID,
          JOB_ID,
          CANDIDATE_ID,
          NULL,                                                     --OFFER_ID
          ASSIGNMENT_TYPE,
          NULL,                                                 --AMENDMENT_ID
          AMENDMENT_IN_PROCESS_NUM,
          ASSIGNMENT_CREATE_DATE,
          ASSIGNMENT_START_DT,
          ASSIGNMENT_END_DT,
          ASSIGNMENT_ACTUAL_END_DT,
          ACTUAL_END_DT_NO_DEFLT,
          NULL,                                    --RELEASED_TO_SUPPLIER_DATE
          NULL,                                    --ACCEPTED_BY_SUPPLIER_DATE
          ASSIGNMENT_EFFECTIVE_DATE,
          LAST_MODIFIED_DATE,
          ASSIGNMENT_DURATION,
          HAS_EVER_BEEN_EFFECTIVE,
          APPROVAL_STATE_ID,
          ASSIGNMENT_STATE_ID,
          APPROVAL_STATE,
          SOURCING_METHOD,
          CANDIDATE_SOURCING_METHOD_ID,
          CURRENT_EDITION_ID,
          CONTACT_INFO_ID,
          CAM_PERSON_ID,
          SAR_PERSON_ID,
          PROJECT_ID,
          PROJECT_AGREEMENT_ID,
          CREATOR_PERSON_ID,
          TIMECARD_APPROVAL_WORKFLOW_ID,
          EVALUATION_ID,
          PROCUREMENT_WKFL_EDITION_ID,
          ASSIGN_REQUISITION_TYPE,
          APPROVAL_WORKFLOW_ID,
          WORKER_ID,
          WORK_ORDER_ID,
          UDF_COLLECTION_ID,
          NULL,                                        --WOV_UDF_COLLECTION_ID
          WORKER_ED_UDF_COLLECTION_ID,
          ONBOARD_ALLOWED,
          ONBOARD_CHECKLIST_ID,
          BUYER_RESOURCE_ID,
          SUPPLIER_RESOURCE_ID,
          ORG_SUB_CLASSIFICATION,
          JC_VALUE,
          JC_TYPE,
          JC_DESCRIPTION,
          JL_VALUE,
          JL_DESCRIPTION,
          ASSIGN_JOB_TITLE,
          ASSIGN_JOB_TITLE_LP,
          NULL,                                              --WAT_DESCRIPTION
          CURRENT_PHASE_TYPE_ID,
          RATE_TYPE_ID,
          RATE_TYPE,
          REG_BILL_RATE,
          OT_BILL_RATE,
          DT_BILL_RATE,
          CUSTOM_BILL_RATE,
          ADJUSTED_BILL_RATE,
          ADJUSTED_OT_RATE,
          ADJUSTED_DT_RATE,
          ADJUSTED_CUSTOM_RATE,
          SUPPLIER_REIMB_BILL_RATE,
          SUPPLIER_OT_REIMB_BILL_RATE,
          SUPPLIER_DT_REIMB_BILL_RATE,
          SUPPLIER_CUST_REIMB_BILL_RATE,
          REG_PAY_RATE,
          OT_PAY_RATE,
          DT_PAY_RATE,
          CUSTOM_PAY_RATE,
          REG_MARK_UP,
          OT_MARK_UP,
          DT_MARK_UP,
          CUSTOM_MARK_UP,
          ASSIGNMENT_CURRENCY_ID,
          ASSIGNMENT_CURRENCY,
          EST_TOTAL_BUDGETED_AMOUNT
     FROM assignment_ea_iqp
   UNION ALL
   SELECT ASSIGNMENT_CONTINUITY_ID,
          CONTRACTOR_PERSON_ID,
          HIRING_MGR_PERSON_ID,
          ACT_HIRING_MGR_PERSON_ID,
          BUYER_ORG_ID,
          SUPPLIER_ORG_ID,
          JOB_ID,
          CANDIDATE_ID,
          NULL,                                                     --OFFER_ID
          ASSIGNMENT_TYPE,
          NULL,                                                 --AMENDMENT_ID
          AMENDMENT_IN_PROCESS_NUM,
          ASSIGNMENT_CREATE_DATE,
          ASSIGNMENT_START_DT,
          ASSIGNMENT_END_DT,
          ASSIGNMENT_ACTUAL_END_DT,
          ACTUAL_END_DT_NO_DEFLT,
          NULL,                                    --RELEASED_TO_SUPPLIER_DATE
          NULL,                                    --ACCEPTED_BY_SUPPLIER_DATE
          ASSIGNMENT_EFFECTIVE_DATE,
          LAST_MODIFIED_DATE,
          ASSIGNMENT_DURATION,
          HAS_EVER_BEEN_EFFECTIVE,
          APPROVAL_STATE_ID,
          ASSIGNMENT_STATE_ID,
          APPROVAL_STATE,
          SOURCING_METHOD,
          CANDIDATE_SOURCING_METHOD_ID,
          CURRENT_EDITION_ID,
          CONTACT_INFO_ID,
          CAM_PERSON_ID,
          SAR_PERSON_ID,
          PROJECT_ID,
          PROJECT_AGREEMENT_ID,
          CREATOR_PERSON_ID,
          TIMECARD_APPROVAL_WORKFLOW_ID,
          EVALUATION_ID,
          PROCUREMENT_WKFL_EDITION_ID,
          ASSIGN_REQUISITION_TYPE,
          APPROVAL_WORKFLOW_ID,
          WORKER_ID,
          WORK_ORDER_ID,
          UDF_COLLECTION_ID,
          NULL,                                        --WOV_UDF_COLLECTION_ID
          WORKER_ED_UDF_COLLECTION_ID,
          ONBOARD_ALLOWED,
          ONBOARD_CHECKLIST_ID,
          BUYER_RESOURCE_ID,
          SUPPLIER_RESOURCE_ID,
          ORG_SUB_CLASSIFICATION,
          JC_VALUE,
          JC_TYPE,
          JC_DESCRIPTION,
          JL_VALUE,
          JL_DESCRIPTION,
          ASSIGN_JOB_TITLE,
          ASSIGN_JOB_TITLE_LP,
          NULL,                                              --WAT_DESCRIPTION
          CURRENT_PHASE_TYPE_ID,
          NULL,                                                 --RATE_TYPE_ID
          NULL,                                                    --RATE_TYPE
          NULL,                                                --REG_BILL_RATE
          NULL,                                                 --OT_BILL_RATE
          NULL,                                                 --DT_BILL_RATE
          NULL,                                             --CUSTOM_BILL_RATE
          NULL,                                           --ADJUSTED_BILL_RATE
          NULL,                                             --ADJUSTED_OT_RATE
          NULL,                                             --ADJUSTED_DT_RATE
          NULL,                                         --ADJUSTED_CUSTOM_RATE
          NULL,                                     --SUPPLIER_REIMB_BILL_RATE
          NULL,                                  --SUPPLIER_OT_REIMB_BILL_RATE
          NULL,                                  --SUPPLIER_DT_REIMB_BILL_RATE
          NULL,                                --SUPPLIER_CUST_REIMB_BILL_RATE
          NULL,                                                 --REG_PAY_RATE
          NULL,                                                  --OT_PAY_RATE
          NULL,                                                  --DT_PAY_RATE
          NULL,                                              --CUSTOM_PAY_RATE
          NULL,                                                  --REG_MARK_UP
          NULL,                                                   --OT_MARK_UP
          NULL,                                                   --DT_MARK_UP
          NULL,                                               --CUSTOM_MARK_UP
          ASSIGNMENT_CURRENCY_ID,
          ASSIGNMENT_CURRENCY,
          EST_TOTAL_BUDGETED_AMOUNT
     FROM assignment_ta_iqp
/