CREATE OR REPLACE FORCE VIEW JOB_VW
(	
    JOB_ID,
    JOB_OPPORTUNITY_ID,
    BUYER_ORG_ID,
    BUYER_ORG_NAME,
    SUPPLIER_ORG_ID,
    SUPPLIER_ORG_NAME,
    ENTERPRISE_ID,
    ENTERPRISE_NAME,
    ENTERPRISE_BUS_ORG_ID,
    HIRING_MGR_PERSON_ID,
    OWNER_PERSON_ID,
    CREATOR_PERSON_ID,
    JOB_STATE_ID,
    PROJECT_AGREEMENT_ID,
    PWFE_AGREEMENT_CREATION_TYPE,
    PROPOSED_APPROVABLE_ASPECTS_ID,
    UDF_COLLECTION_ID,
    TEMPLATE_AVAILABILITY,
    ALLOW_OVERFILL,
    ALLOW_OVERFILL_ZERO_POSITION,
    ALLOW_OVERFILL_NULL_POSITION,
    OVERFILL_TOLERANCE,
    OVERFILL_TOLERANCE_TYPE,
    JOB_POSITION_TITLE,
    JOB_DESCRIPTION_LP,
    JOB_POSITION_TITLE_LP,
    JC_VALUE,
    JC_TYPE,
    JC_DESCRIPTION,
    ORG_SUB_CLASSIFICATION,
    JOB_CREATE_DATE,
    JOB_OPPORTUNITY_CREATE_DATE,
    APPROVED_DATE,
    JOB_SUB_MATCHING_DATE,
    JOB_START_DATE,
    JOB_ARCHIVED_DATE,
    JOB_DURATION_MIN,
    JOB_DURATION_MAX,
    JOB_DURATION_UNIT,
    JOB_SOURCE_OF_RECORD,
    JOB_STATE,
    JOB_OPPORTUNITY_STATE,
    JOB_APPROVAL_STATUS_ID,
    JOB_APPROVAL_STATUS,
    JL_VALUE,
    JL_TYPE,
    JOB_LEVEL_DESC,
    JOB_TYPE,
    JOB_DESCRIPTION,
    JOB_TEMPLATE_DESCRIPTION,
    JOB_REQUISITION_TYPE,
    JOB_PRIORITY_ID,
    JOB_PRIORITY,
    PHASE_TYPE_ID,
    JOB_SUBMISSION_ID,
    JOB_LAST_MODIFIED_DATE,
    JOB_OPPORTUNITY_LAST_MOD_DATE,
    GREATEST_LAST_MODIFIED_DATE
   ) 
AS SELECT    	
      job.job_id,
      jo.job_opportunity_id,
      jo.buyer_org_id,
      buyer.bus_org_name AS buyer_org_name,
      jo.supplier_org_id,
      supp.bus_org_name AS supplier_org_name,
      buyer.enterprise_id,
      buyer.enterprise_name,
      buyer.enterprise_bus_org_id,
      job.hiring_mgr_person_id,
      job.owner_person_id,
      job.creator_person_id,
      job.job_state_id,
      job.project_agreement_id,
      job.pwfe_agreement_creation_type,
      job.proposed_approvable_aspects_id,
      job.udf_collection_id,
      job.template_availability,
      job.allow_overfill,
      job.allow_overfill_zero_position,
      job.allow_overfill_null_position,
      job.overfill_tolerance,
      job.overfill_tolerance_type,
      job.job_position_title,
      job.job_description_lp,
      job.job_position_title_lp,
      job.jc_value,
      job.jc_type,
      job.jc_description,
      job.org_sub_classification,
      job.job_created_date,
      jo.create_date,
      job.approved_date,
      job.job_sub_matching_date,
      job.job_start_date,
      job.job_archived_date,
      job.job_duration_min,
      job.job_duration_max,
      job.job_duration_unit,
      job.job_source_of_record,
      job.job_state,
      jo.state,
      job.job_approval_status_id,
      job.job_approval_status,
      job.jl_value,
      job.jl_type,
      job.job_level_desc,
      job.job_type,
      job.job_description,
      job.job_template_description,
      job.job_requisition_type,
      job.job_priority_id,
      job.job_priority,
      job.phase_type_id,
      jo.job_submission_id,
      job.last_modified_date,
      jo.last_modified_date,
      GREATEST(job.last_modified_date,jo.last_modified_date) as greatest_last_modified_date
FROM
     operationalstore.job_iqp job,
     operationalstore.job_opportunity_iqp jo,
     operationalstore.bus_org_iqp buyer,
     operationalstore.bus_org_iqp supp
WHERE
      GREATEST(job.last_modified_date,jo.last_modified_date) >=  ADD_MONTHS(SYSDATE, - 25)
  AND jo.job_id(+)           = job.job_id
  AND buyer.bus_org_id(+)    =  jo.buyer_org_id
  AND supp.bus_org_id(+)     =  jo.supplier_org_id
/


  