UPDATE (SELECT COE.METRIC_ID AS OLD_METRIC_ID,
               COE.CLIENT_GUID AS OLD_CLIENT_GUID,
               con.METRIC_ID AS NEW_METRIC_ID,
               con.CLIENT_GUID AS NEW_CLIENT_GUID
          FROM CLIENT_METRIC_COEFFICIENT COE, CLIENT_METRIC_CONVERSION con
         WHERE COE.CLIENT_METRIC_COEFFICIENT_GUID =
                  con.CLIENT_METRIC_COEFFICIENT_GUID)
   SET NEW_METRIC_ID = OLD_METRIC_ID, NEW_CLIENT_GUID = OLD_CLIENT_GUID
/
COMMIT
/
