drop index RATE_AND_TTF_BENCHMARKS_IDX01
/
alter table RATE_AND_TTF_BENCHMARKS DROP COLUMN STD_JOB_CATEGORY_ID
/
CREATE INDEX RATE_AND_TTF_BENCHMARKS_IDX01 ON RATE_AND_TTF_BENCHMARKS (BENCHMARK_TYPE, STD_OCCUPATION_ID, PLACE_ID)
/