
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0580','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2030','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3440','U.S. Rate Benchmarks',39,'USD',16,22,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5240','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2580','U.S. Rate Benchmarks',39,'USD',16,22,26,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3700','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4400','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8520','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2840','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4940','U.S. Rate Benchmarks',39,'USD',14,21,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6690','U.S. Rate Benchmarks',39,'USD',15,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7320','U.S. Rate Benchmarks',39,'USD',19,26,33,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7480','U.S. Rate Benchmarks',39,'USD',18,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8780','U.S. Rate Benchmarks',39,'USD',14,21,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2082','U.S. Rate Benchmarks',39,'USD',19,25,32,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2995','U.S. Rate Benchmarks',39,'USD',15,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3280','U.S. Rate Benchmarks',39,'USD',18,25,32,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8872','U.S. Rate Benchmarks',39,'USD',21,28,35,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2190','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2700','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2900','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3980','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4992','U.S. Rate Benchmarks',39,'USD',19,25,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5960','U.S. Rate Benchmarks',39,'USD',18,24,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6080','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7510','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8280','U.S. Rate Benchmarks',39,'USD',18,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0500','U.S. Rate Benchmarks',39,'USD',15,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0600','U.S. Rate Benchmarks',39,'USD',15,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4680','U.S. Rate Benchmarks',39,'USD',14,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7520','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1360','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2200','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7720','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1080','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1040','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1602','U.S. Rate Benchmarks',39,'USD',19,26,32,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2040','U.S. Rate Benchmarks',39,'USD',14,20,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6880','U.S. Rate Benchmarks',39,'USD',15,21,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1020','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2440','U.S. Rate Benchmarks',39,'USD',16,22,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3480','U.S. Rate Benchmarks',39,'USD',18,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3920','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8320','U.S. Rate Benchmarks',39,'USD',14,20,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8440','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4280','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0220','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3880','U.S. Rate Benchmarks',39,'USD',16,23,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5200','U.S. Rate Benchmarks',39,'USD',15,21,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7680','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1122','U.S. Rate Benchmarks',39,'USD',21,28,35,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1900','U.S. Rate Benchmarks',39,'USD',13,19,25,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0870','U.S. Rate Benchmarks',39,'USD',15,21,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3000','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3520','U.S. Rate Benchmarks',39,'USD',15,21,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4040','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2240','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6820','U.S. Rate Benchmarks',39,'USD',18,24,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1740','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7920','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0920','U.S. Rate Benchmarks',39,'USD',15,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0880','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5140','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1520','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3120','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3290','U.S. Rate Benchmarks',39,'USD',15,22,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3605','U.S. Rate Benchmarks',39,'USD',15,22,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('9200','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2520','U.S. Rate Benchmarks',39,'USD',18,24,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4360','U.S. Rate Benchmarks',39,'USD',18,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0200','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7490','U.S. Rate Benchmarks',39,'USD',16,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6720','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0960','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2335','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5602','U.S. Rate Benchmarks',39,'USD',22,29,35,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8160','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1320','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1642','U.S. Rate Benchmarks',39,'USD',18,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1840','U.S. Rate Benchmarks',39,'USD',18,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4320','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8080','U.S. Rate Benchmarks',39,'USD',14,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('9320','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5880','U.S. Rate Benchmarks',39,'USD',18,24,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2400','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6442','U.S. Rate Benchmarks',39,'USD',19,25,32,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2360','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3680','U.S. Rate Benchmarks',39,'USD',15,21,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6162','U.S. Rate Benchmarks',39,'USD',20,26,33,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6680','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7560','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('9140','U.S. Rate Benchmarks',39,'USD',15,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6480','U.S. Rate Benchmarks',39,'USD',18,25,32,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1760','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3160','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8140','U.S. Rate Benchmarks',39,'USD',14,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7760','U.S. Rate Benchmarks',39,'USD',18,24,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1660','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3660','U.S. Rate Benchmarks',39,'USD',15,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5360','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0640','U.S. Rate Benchmarks',39,'USD',19,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1880','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2320','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4080','U.S. Rate Benchmarks',39,'USD',15,21,26,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4880','U.S. Rate Benchmarks',39,'USD',15,21,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7240','U.S. Rate Benchmarks',39,'USD',18,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8640','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6520','U.S. Rate Benchmarks',39,'USD',18,24,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4640','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6800','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6740','U.S. Rate Benchmarks',39,'USD',15,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('9260','U.S. Rate Benchmarks',39,'USD',14,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3620','U.S. Rate Benchmarks',39,'USD',15,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5082','U.S. Rate Benchmarks',39,'USD',18,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7620','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6020','U.S. Rate Benchmarks',39,'USD',14,20,26,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1580','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4920','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0320','U.S. Rate Benchmarks',39,'USD',17,23,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1240','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1922','U.S. Rate Benchmarks',39,'USD',19,25,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3810','U.S. Rate Benchmarks',39,'USD',16,22,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4600','U.S. Rate Benchmarks',39,'USD',17,23,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5800','U.S. Rate Benchmarks',39,'USD',16,22,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7640','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8750','U.S. Rate Benchmarks',39,'USD',15,20,25,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('9080','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1540','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6760','U.S. Rate Benchmarks',39,'USD',18,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1305','U.S. Rate Benchmarks',39,'USD',19,25,32,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7602','U.S. Rate Benchmarks',39,'USD',20,26,33,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0460','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3080','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4720','U.S. Rate Benchmarks',39,'USD',18,25,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8940','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3400','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1350','U.S. Rate Benchmarks',39,'USD',16,22,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0380','U.S. Rate Benchmarks',39,'USD',17,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1000','U.S. Rate Benchmarks',39,'USD',17,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2180','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5160','U.S. Rate Benchmarks',39,'USD',15,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8600','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2720','U.S. Rate Benchmarks',39,'USD',15,21,26,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6200','U.S. Rate Benchmarks',39,'USD',18,24,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0680','U.S. Rate Benchmarks',39,'USD',15,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4472','U.S. Rate Benchmarks',39,'USD',20,27,34,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5170','U.S. Rate Benchmarks',39,'USD',15,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6922','U.S. Rate Benchmarks',39,'USD',18,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7362','U.S. Rate Benchmarks',39,'USD',22,29,36,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8120','U.S. Rate Benchmarks',39,'USD',15,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1720','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2670','U.S. Rate Benchmarks',39,'USD',18,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6560','U.S. Rate Benchmarks',39,'USD',14,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5520','U.S. Rate Benchmarks',39,'USD',17,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2020','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2710','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3600','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4900','U.S. Rate Benchmarks',39,'USD',15,21,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5790','U.S. Rate Benchmarks',39,'USD',14,20,26,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6015','U.S. Rate Benchmarks',39,'USD',14,20,26,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6580','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8240','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0120','U.S. Rate Benchmarks',39,'USD',14,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0520','U.S. Rate Benchmarks',39,'USD',18,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1800','U.S. Rate Benchmarks',39,'USD',15,21,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3320','U.S. Rate Benchmarks',39,'USD',21,28,34,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2120','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3500','U.S. Rate Benchmarks',39,'USD',18,25,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8920','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6340','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1400','U.S. Rate Benchmarks',39,'USD',16,22,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1960','U.S. Rate Benchmarks',39,'USD',16,22,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6120','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7880','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2330','U.S. Rate Benchmarks',39,'USD',16,22,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2760','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7800','U.S. Rate Benchmarks',39,'USD',15,22,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4150','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('9040','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4520','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0760','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3960','U.S. Rate Benchmarks',39,'USD',15,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5560','U.S. Rate Benchmarks',39,'USD',18,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0740','U.S. Rate Benchmarks',39,'USD',17,24,32,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8000','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6400','U.S. Rate Benchmarks',39,'USD',18,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2162','U.S. Rate Benchmarks',39,'USD',17,23,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3720','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6960','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5120','U.S. Rate Benchmarks',39,'USD',20,26,32,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6980','U.S. Rate Benchmarks',39,'USD',17,23,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3760','U.S. Rate Benchmarks',39,'USD',18,24,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7040','U.S. Rate Benchmarks',39,'USD',18,24,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3560','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3040','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0480','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2560','U.S. Rate Benchmarks',39,'USD',15,21,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3150','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6640','U.S. Rate Benchmarks',39,'USD',18,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1010','U.S. Rate Benchmarks',39,'USD',18,24,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2985','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5920','U.S. Rate Benchmarks',39,'USD',17,23,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4100','U.S. Rate Benchmarks',39,'USD',15,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4120','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0160','U.S. Rate Benchmarks',39,'USD',18,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1280','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2975','U.S. Rate Benchmarks',39,'USD',15,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6840','U.S. Rate Benchmarks',39,'USD',17,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8680','U.S. Rate Benchmarks',39,'USD',16,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1692','U.S. Rate Benchmarks',39,'USD',18,24,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2000','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4800','U.S. Rate Benchmarks',39,'USD',14,21,26,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8400','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4200','U.S. Rate Benchmarks',39,'USD',16,22,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8560','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4890','U.S. Rate Benchmarks',39,'USD',15,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0240','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3240','U.S. Rate Benchmarks',39,'USD',17,24,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4000','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6280','U.S. Rate Benchmarks',39,'USD',18,24,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8050','U.S. Rate Benchmarks',39,'USD',18,24,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('9280','U.S. Rate Benchmarks',39,'USD',16,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1440','U.S. Rate Benchmarks',39,'USD',17,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2655','U.S. Rate Benchmarks',39,'USD',15,21,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5330','U.S. Rate Benchmarks',39,'USD',15,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('6660','U.S. Rate Benchmarks',39,'USD',17,23,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1560','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3580','U.S. Rate Benchmarks',39,'USD',15,21,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3840','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0040','U.S. Rate Benchmarks',39,'USD',16,22,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0840','U.S. Rate Benchmarks',39,'USD',15,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3362','U.S. Rate Benchmarks',39,'USD',19,25,31,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('4420','U.S. Rate Benchmarks',39,'USD',16,22,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7200','U.S. Rate Benchmarks',39,'USD',16,22,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8360','U.S. Rate Benchmarks',39,'USD',15,21,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('8800','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7160','U.S. Rate Benchmarks',39,'USD',18,24,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('5720','U.S. Rate Benchmarks',39,'USD',17,24,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('0860','U.S. Rate Benchmarks',39,'USD',16,23,30,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('7840','U.S. Rate Benchmarks',39,'USD',16,22,29,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('2290','U.S. Rate Benchmarks',39,'USD',16,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('3870','U.S. Rate Benchmarks',39,'USD',16,22,27,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('1480','U.S. Rate Benchmarks',39,'USD',15,22,28,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
Insert into SOS_IQNLABS_MA_BENCH (CMSA_CODE,BENCHMARK_TYPE,STD_OCCUPATION_ID,UNIT,BENCHMARK_25_PERCENTILE,BENCHMARK_50_PERCENTILE,BENCHMARK_75_PERCENTILE,LOAD_DATE,EFFECTIVE_DATE,END_DATE) values ('9000','U.S. Rate Benchmarks',39,'USD',15,21,26,sysdate,to_date('01-JAN-17','DD-MON-RR'),null)
/
