-- 08/09/2016 IQN-33780 jpullifrone 


--LEGO_ASSIGN_PAYMENT_REQUEST
INSERT INTO lego_refresh_index (object_name, source_name, index_name, index_type, column_list)
    VALUES ('LEGO_ASSIGN_PAYMENT_REQUEST','USPROD','ASSIGN_PAYMENT_REQ_IQP_U01','NONUNIQUE','PAYMENT_REQUEST_ID')
/  
INSERT INTO lego_refresh_index (object_name, source_name, index_name, index_type, column_list)
    VALUES ('LEGO_ASSIGN_PAYMENT_REQUEST','WFPROD','ASSIGN_PAYMENT_REQ_WF_U01','NONUNIQUE','PAYMENT_REQUEST_ID')
/
--LEGO_TIMECARD_APPROVAL
INSERT INTO lego_refresh_index (object_name, source_name, index_name, index_type, column_list)
    VALUES ('LEGO_TIMECARD_APPROVAL','USPROD','TIMECARD_APPROVAL_IQP_U01','UNIQUE','TIMECARD_ID')
/  
INSERT INTO lego_refresh_index (object_name, source_name, index_name, index_type, column_list)
    VALUES ('LEGO_TIMECARD_APPROVAL','WFPROD','TIMECARD_APPROVAL_WF_U01','UNIQUE','TIMECARD_ID')
/ 
--LEGO_EXPENSE_APPROVAL
INSERT INTO lego_refresh_index (object_name, source_name, index_name, index_type, column_list)
    VALUES ('LEGO_EXPENSE_APPROVAL','USPROD','EXPENSE_APPROVAL_IQP_U01','UNIQUE','EXPENSE_REPORT_ID')
/  
INSERT INTO lego_refresh_index (object_name, source_name, index_name, index_type, column_list)
    VALUES ('LEGO_EXPENSE_APPROVAL','WFPROD','EXPENSE_APPROVAL_WF_U01','UNIQUE','EXPENSE_REPORT_ID')
/
--LEGO_SOW_MILESTONE_INVOICE
UPDATE lego_refresh_index
   SET column_list = 'MILESTONE_INVOICE_ID,APPROVER_PERSON_ID,APPROVED_DATE,SOW_SPEND_CATEGORY,SOW_SPEND_TYPE'
 WHERE object_name = 'LEGO_SOW_MILESTONE_INVOICE'
/
--LEGO_ASSIGNMENT_WO
UPDATE lego_refresh_index
   SET column_list = 'ASSIGNMENT_CONTINUITY_ID,ASSIGNMENT_TYPE,JOB_ID,JC_DESCRIPTION,JL_DESCRIPTION,CONTRACTOR_PERSON_ID,HIRING_MGR_PERSON_ID,ASSIGN_JOB_TITLE,ASSIGNMENT_START_DT,ASSIGNMENT_ACTUAL_END_DT,SUPPLIER_RESOURCE_ID'
 WHERE object_name = 'LEGO_ASSIGNMENT_WO'
/
--LEGO_ASSIGNMENT_EA
UPDATE lego_refresh_index
   SET column_list = 'ASSIGNMENT_CONTINUITY_ID,ASSIGNMENT_TYPE,JOB_ID,JC_DESCRIPTION,JL_DESCRIPTION,CONTRACTOR_PERSON_ID,HIRING_MGR_PERSON_ID,ASSIGN_JOB_TITLE,ASSIGNMENT_START_DT,ASSIGNMENT_ACTUAL_END_DT,SUPPLIER_RESOURCE_ID'
 WHERE object_name = 'LEGO_ASSIGNMENT_EA'
/
COMMIT
/



