CREATE TABLE lego_invoiced_expd_detail (
buyer_org_id                   NUMBER(38) NOT NULL,
supplier_org_id                NUMBER(38) NOT NULL,
invoice_id                     NUMBER(38) NOT NULL,
invoice_header_id              NUMBER(38) NOT NULL,
invoice_detail_id              NUMBER(38) NOT NULL,
invoice_date                   DATE NOT NULL,
invoice_create_date            DATE NOT NULL,               
expenditure_item_id            NUMBER(38) NOT NULL,
expenditure_number             VARCHAR2(24) NOT NULL,
expenditure_date               DATE NOT NULL,
week_ending_date               DATE NOT NULL,
assignment_continuity_id       NUMBER(38),                  
timecard_id                    NUMBER(38),
timecard_entry_id              NUMBER(38),  
assignment_bonus_id            NUMBER(38),
payment_request_id             NUMBER(38),
payment_request_invdtl_id      NUMBER(38),
expense_report_id              NUMBER(38),
expense_report_line_item_id    NUMBER(38),               
direct_hire_agmt_id            NUMBER(38),
project_agreement_id           NUMBER(38),               
milestone_invoice_id           NUMBER(38), 
milestone_invoice_detail_id    NUMBER(38),
customer_supplier_internal_id  VARCHAR2(128),
accounting_code                VARCHAR2(500),
buyer_resource_id              VARCHAR2(64),
ap_invoice_number              VARCHAR2(128),
is_vat_applied_on_fee          NUMBER(1),          
buyer_fee                      NUMBER(38,2), 
supplier_fee                   NUMBER(38,2),    
flexrate_mgmt_fee_amount       NUMBER(38,2),
buyer_fee_calc_percent         NUMBER(38,2),
supplier_fee_calc_percent      NUMBER(38,2),                    
flexrate_type                  VARCHAR2(24),
invoice_transaction_type       VARCHAR2(64),
expense_type_name              VARCHAR2(64),
payment_type_name              VARCHAR2(64),
invalidating_event_desc_id     NUMBER(38),  
reversed_expenditure_txn_id    NUMBER(38),
invoiceable_mgmt_fee_txn_id    NUMBER(38),
custom_expenditure_type_id     NUMBER(38),
partial_rate_percent           NUMBER(38,2),
flexrate_exp_type_name         VARCHAR2(64),
service_id                     NUMBER(38),
service_identifier             VARCHAR2(64),
service_exp_type_desc          VARCHAR2(64),
service_exp_type_id            NUMBER(38),
purchase_order                 VARCHAR2(64),
supplier_reference_num         VARCHAR2(64),
debit_credit_indicator         NUMBER(1),
project_number                 VARCHAR2(500), 
buyer_bus_org_bill_to_addr_id  NUMBER(38),                     
buyer_taxable_country_id       NUMBER(38),
buyer_bus_org_tax_id           VARCHAR2(64),
supplier_bus_org_tax_id        VARCHAR2(64),
supplier_taxable_country_id    NUMBER(38),
is_iqn_mgmt_fee_payee          NUMBER(1),              
cac1_segment1_value            VARCHAR2(254),
cac1_segment2_value            VARCHAR2(254),
cac1_segment3_value            VARCHAR2(254),
cac1_segment4_value            VARCHAR2(254),
cac1_segment5_value            VARCHAR2(254),
cac2_segment1_value            VARCHAR2(254),
cac2_segment2_value            VARCHAR2(254),
cac2_segment3_value            VARCHAR2(254),
cac2_segment4_value            VARCHAR2(254),
cac2_segment5_value            VARCHAR2(254),            
rate_unit_id                   NUMBER(38),
rate_identifier_id             NUMBER(38),
rate_identifier_name           VARCHAR2(64),
base_bill_rate                 NUMBER(38,2),
base_pay_rate                  NUMBER(38,2),
buyer_adjusted_bill_rate       NUMBER(38,2),
supplier_reimbursement_rate    NUMBER(38,2),
flexrate_buyer_rate            NUMBER(38,2),
flexrate_supplier_rate         NUMBER(38,2), 
quantity                       NUMBER(38,2),
buyer_adjusted_amount          NUMBER(38,2),
supplier_reimbursement_amount  NUMBER(38,2),
flexrate_buyer_amount          NUMBER(38,2),
flexrate_supplier_amount       NUMBER(38,2),
curr_conv_info_id              NUMBER(38),
currency                       VARCHAR2(64),
owning_buyer_org_id            NUMBER(38) NOT NULL,
buyer_enterprise_bus_org_id    NUMBER(38) NOT NULL,
data_source                    VARCHAR2(24) NOT NULL,
detail_load_date               DATE NOT NULL)         
  PARTITION BY LIST (buyer_org_id)    
  SUBPARTITION BY HASH (invoice_date) SUBPARTITIONS 16
     (PARTITION P_NULL VALUES (NULL))
/
