-- 08/10/2016 IQN-33780 jpullifrone 

--LEGO_ASSIGNMENT_WO
UPDATE lego_refresh_index
   SET column_list = 'ASSIGNMENT_CONTINUITY_ID,ASSIGNMENT_TYPE,JOB_ID,CONTRACTOR_PERSON_ID,ASSIGN_JOB_TITLE,JC_DESCRIPTION,JL_DESCRIPTION,ASSIGNMENT_START_DT,ASSIGNMENT_ACTUAL_END_DT,SUPPLIER_RESOURCE_ID'
 WHERE object_name = 'LEGO_ASSIGNMENT_WO'
/
--LEGO_ASSIGNMENT_EA
UPDATE lego_refresh_index
   SET column_list = 'ASSIGNMENT_CONTINUITY_ID,ASSIGNMENT_TYPE,JOB_ID,CONTRACTOR_PERSON_ID,ASSIGN_JOB_TITLE,JC_DESCRIPTION,JL_DESCRIPTION,ASSIGNMENT_START_DT,ASSIGNMENT_ACTUAL_END_DT,SUPPLIER_RESOURCE_ID'
 WHERE object_name = 'LEGO_ASSIGNMENT_EA'
/
COMMIT
/



