/***********************************[SUPPLIER_RELEASE_DUPLICATES]***********************************/

CREATE TABLE "SUPPLIER_SCORECARD"."SUPPLIER_RELEASE_DUPLICATES" 
   (	"RELEASE_GUID" RAW(17) NOT NULL ENABLE, 
	"CLIENT_GUID" RAW(17) NOT NULL ENABLE, 
	"CLIENT_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"SUPPLIER_GUID" RAW(17) NOT NULL ENABLE, 
	"SUPPLIER_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"RELEASE_DATE" DATE NOT NULL ENABLE, 
	"REQUISITION_GUID" RAW(17) NOT NULL ENABLE, 
	"REQUISITION_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"REQUISITION_CREATE_DATE" DATE NOT NULL ENABLE, 
	"REQUISITION_CURRENCY" VARCHAR2(50) NOT NULL ENABLE, 
	"REQUISITION_TITLE" VARCHAR2(255), 
	"REQUISITION_INDUSTRY" VARCHAR2(255), 
	"REQUISITION_COUNTRY" VARCHAR2(100), 
	"REQUISITION_STATE" VARCHAR2(100), 
	"REQUISITION_CITY" VARCHAR2(100), 
	"RELEASE_TIER" VARCHAR2(255), 
	"REQUISITION_POSITIONS" NUMBER, 
	"REQUISITION_RATE" NUMBER, 
	"DATABASE_NAME" VARCHAR2(128),
    "INSERT_DATE" DATE NOT NULL ENABLE
   )
 /