CREATE TABLE "PROCESSING_LOG" 
   (	"LOG_GUID" RAW(16) NOT NULL ENABLE, 
	"LOG_DATE" DATE DEFAULT SYS_EXTRACT_UTC (SYSTIMESTAMP) NOT NULL ENABLE, 
	"TRACE_LEVEL" VARCHAR2(20 CHAR) DEFAULT 'ERROR' NOT NULL ENABLE, 
	"INSTANCE_NAME" VARCHAR2(16 CHAR), 
	"SID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"SERIAL#" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30 CHAR) DEFAULT 'ORACLE' NOT NULL ENABLE, 
	"OSUSER" VARCHAR2(30 CHAR) DEFAULT 'ORACLE' NOT NULL ENABLE, 
	"SOURCE" VARCHAR2(61 CHAR) NOT NULL ENABLE, 
	"CODE_LOCATION" VARCHAR2(200 CHAR), 
	"START_TIME" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC (SYSTIMESTAMP) NOT NULL ENABLE, 
	"END_TIME" TIMESTAMP (6), 
	"PARENT_LOG_GUID" RAW(16), 
	"TRANSACTION_RESULT" VARCHAR2(30 CHAR), 
	"ERROR_CODE" NUMBER, 
	"MESSAGE" VARCHAR2(4000 CHAR) NOT NULL ENABLE, 
	"MESSAGE_CLOB" CLOB, 
	 CONSTRAINT "PROCESSING_LOG_PK" PRIMARY KEY ("LOG_GUID"), 
	 CONSTRAINT "PROCESSING_LOG_FK" FOREIGN KEY ("PARENT_LOG_GUID")
	  REFERENCES "PROCESSING_LOG" ("LOG_GUID") ON DELETE CASCADE ENABLE NOVALIDATE
   ) 
  PARTITION BY RANGE ("LOG_DATE") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) 
 (PARTITION "PROCESSING_LOG_RP201701"  
     VALUES LESS THAN (TO_DATE(' 2017-02-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
  SEGMENT CREATION DEFERRED 
 ) 
/



